// Code generated by ent, DO NOT EDIT.

package transferchunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transferchunk type in the database.
	Label = "transfer_chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransferID holds the string denoting the transfer_id field in the database.
	FieldTransferID = "transfer_id"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the transferchunk in the database.
	Table = "transfer_chunks"
)

// Columns holds all SQL columns for transferchunk fields.
var Columns = []string{
	FieldID,
	FieldTransferID,
	FieldSeq,
	FieldData,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TransferIDValidator is a validator for the "transfer_id" field. It is called by the builders before save.
	TransferIDValidator func(string) error
	// SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	SeqValidator func(int) error
	// DataValidator is a validator for the "data" field. It is called by the builders before save.
	DataValidator func([]byte) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the TransferChunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTransferID orders the results by the transfer_id field.
func ByTransferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransferID, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
