// Code generated by ent, DO NOT EDIT.

package transfersignal

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transfersignal type in the database.
	Label = "transfer_signal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransferID holds the string denoting the transfer_id field in the database.
	FieldTransferID = "transfer_id"
	// FieldFromClientID holds the string denoting the from_client_id field in the database.
	FieldFromClientID = "from_client_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the transfersignal in the database.
	Table = "transfer_signals"
)

// Columns holds all SQL columns for transfersignal fields.
var Columns = []string{
	FieldID,
	FieldTransferID,
	FieldFromClientID,
	FieldKind,
	FieldPayload,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TransferIDValidator is a validator for the "transfer_id" field. It is called by the builders before save.
	TransferIDValidator func(string) error
	// FromClientIDValidator is a validator for the "from_client_id" field. It is called by the builders before save.
	FromClientIDValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the TransferSignal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTransferID orders the results by the transfer_id field.
func ByTransferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransferID, opts...).ToFunc()
}

// ByFromClientID orders the results by the from_client_id field.
func ByFromClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromClientID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
