// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/enrollmenttoken"
)

// EnrollmentTokenCreate is the builder for creating a EnrollmentToken entity.
type EnrollmentTokenCreate struct {
	config
	mutation *EnrollmentTokenMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *EnrollmentTokenCreate) SetTenantID(v string) *EnrollmentTokenCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableTenantID(v *string) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *EnrollmentTokenCreate) SetLabel(v string) *EnrollmentTokenCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableLabel(v *string) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *EnrollmentTokenCreate) SetTokenHash(v string) *EnrollmentTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EnrollmentTokenCreate) SetExpiresAt(v time.Time) *EnrollmentTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableExpiresAt(v *time.Time) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *EnrollmentTokenCreate) SetMaxUses(v int) *EnrollmentTokenCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableMaxUses(v *int) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUseCount sets the "use_count" field.
func (_c *EnrollmentTokenCreate) SetUseCount(v int) *EnrollmentTokenCreate {
	_c.mutation.SetUseCount(v)
	return _c
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableUseCount(v *int) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetUseCount(*v)
	}
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *EnrollmentTokenCreate) SetRevoked(v bool) *EnrollmentTokenCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableRevoked(v *bool) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnrollmentTokenCreate) SetCreatedAt(v time.Time) *EnrollmentTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnrollmentTokenCreate) SetNillableCreatedAt(v *time.Time) *EnrollmentTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnrollmentTokenCreate) SetID(v string) *EnrollmentTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EnrollmentTokenMutation object of the builder.
func (_c *EnrollmentTokenCreate) Mutation() *EnrollmentTokenMutation {
	return _c.mutation
}

// Save creates the EnrollmentToken in the database.
func (_c *EnrollmentTokenCreate) Save(ctx context.Context) (*EnrollmentToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnrollmentTokenCreate) SaveX(ctx context.Context) *EnrollmentToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrollmentTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrollmentTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnrollmentTokenCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := enrollmenttoken.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Label(); !ok {
		v := enrollmenttoken.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := enrollmenttoken.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		v := enrollmenttoken.DefaultUseCount
		_c.mutation.SetUseCount(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := enrollmenttoken.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enrollmenttoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnrollmentTokenCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "EnrollmentToken.tenant_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "EnrollmentToken.label"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "EnrollmentToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := enrollmenttoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "EnrollmentToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "EnrollmentToken.max_uses"`)}
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		return &ValidationError{Name: "use_count", err: errors.New(`ent: missing required field "EnrollmentToken.use_count"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "EnrollmentToken.revoked"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnrollmentToken.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := enrollmenttoken.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EnrollmentToken.id": %w`, err)}
		}
	}
	return nil
}

func (_c *EnrollmentTokenCreate) sqlSave(ctx context.Context) (*EnrollmentToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EnrollmentToken.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnrollmentTokenCreate) createSpec() (*EnrollmentToken, *sqlgraph.CreateSpec) {
	var (
		_node = &EnrollmentToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enrollmenttoken.Table, sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(enrollmenttoken.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(enrollmenttoken.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(enrollmenttoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(enrollmenttoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(enrollmenttoken.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UseCount(); ok {
		_spec.SetField(enrollmenttoken.FieldUseCount, field.TypeInt, value)
		_node.UseCount = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(enrollmenttoken.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enrollmenttoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// EnrollmentTokenCreateBulk is the builder for creating many EnrollmentToken entities in bulk.
type EnrollmentTokenCreateBulk struct {
	config
	err      error
	builders []*EnrollmentTokenCreate
}

// Save creates the EnrollmentToken entities in the database.
func (_c *EnrollmentTokenCreateBulk) Save(ctx context.Context) ([]*EnrollmentToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnrollmentToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnrollmentTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnrollmentTokenCreateBulk) SaveX(ctx context.Context) []*EnrollmentToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrollmentTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrollmentTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
