// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/enrollmenttoken"
	"github.com/mcmx/nitejaguar/ent/predicate"
)

// EnrollmentTokenDelete is the builder for deleting a EnrollmentToken entity.
type EnrollmentTokenDelete struct {
	config
	hooks    []Hook
	mutation *EnrollmentTokenMutation
}

// Where appends a list predicates to the EnrollmentTokenDelete builder.
func (_d *EnrollmentTokenDelete) Where(ps ...predicate.EnrollmentToken) *EnrollmentTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EnrollmentTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnrollmentTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EnrollmentTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enrollmenttoken.Table, sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EnrollmentTokenDeleteOne is the builder for deleting a single EnrollmentToken entity.
type EnrollmentTokenDeleteOne struct {
	_d *EnrollmentTokenDelete
}

// Where appends a list predicates to the EnrollmentTokenDelete builder.
func (_d *EnrollmentTokenDeleteOne) Where(ps ...predicate.EnrollmentToken) *EnrollmentTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EnrollmentTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enrollmenttoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnrollmentTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
