// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mcmx/nitejaguar/ent/nodeassignment"
)

// NodeAssignment is the model entity for the NodeAssignment schema.
type NodeAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID string `json:"workflow_id,omitempty"`
	// ExecutionID holds the value of the "execution_id" field.
	ExecutionID string `json:"execution_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// parent result payload forwarded as $input, JSON-encoded
	PayloadJSON string `json:"payload_json,omitempty"`
	// ParentActionID holds the value of the "parent_action_id" field.
	ParentActionID string `json:"parent_action_id,omitempty"`
	// pending or done
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeassignment.FieldID, nodeassignment.FieldTenantID, nodeassignment.FieldWorkflowID, nodeassignment.FieldExecutionID, nodeassignment.FieldNodeID, nodeassignment.FieldPayloadJSON, nodeassignment.FieldParentActionID, nodeassignment.FieldStatus:
			values[i] = new(sql.NullString)
		case nodeassignment.FieldCreatedAt, nodeassignment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeAssignment fields.
func (_m *NodeAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeassignment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case nodeassignment.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case nodeassignment.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				_m.WorkflowID = value.String
			}
		case nodeassignment.FieldExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = value.String
			}
		case nodeassignment.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case nodeassignment.FieldPayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_json", values[i])
			} else if value.Valid {
				_m.PayloadJSON = value.String
			}
		case nodeassignment.FieldParentActionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_action_id", values[i])
			} else if value.Valid {
				_m.ParentActionID = value.String
			}
		case nodeassignment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case nodeassignment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nodeassignment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *NodeAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NodeAssignment.
// Note that you need to call NodeAssignment.Unwrap() before calling this method if this NodeAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeAssignment) Update() *NodeAssignmentUpdateOne {
	return NewNodeAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeAssignment) Unwrap() *NodeAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("NodeAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(_m.WorkflowID)
	builder.WriteString(", ")
	builder.WriteString("execution_id=")
	builder.WriteString(_m.ExecutionID)
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("payload_json=")
	builder.WriteString(_m.PayloadJSON)
	builder.WriteString(", ")
	builder.WriteString("parent_action_id=")
	builder.WriteString(_m.ParentActionID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NodeAssignments is a parsable slice of NodeAssignment.
type NodeAssignments []*NodeAssignment
