// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/nodeassignment"
	"github.com/mcmx/nitejaguar/ent/predicate"
)

// NodeAssignmentUpdate is the builder for updating NodeAssignment entities.
type NodeAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *NodeAssignmentMutation
}

// Where appends a list predicates to the NodeAssignmentUpdate builder.
func (_u *NodeAssignmentUpdate) Where(ps ...predicate.NodeAssignment) *NodeAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *NodeAssignmentUpdate) SetTenantID(v string) *NodeAssignmentUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableTenantID(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *NodeAssignmentUpdate) SetWorkflowID(v string) *NodeAssignmentUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableWorkflowID(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *NodeAssignmentUpdate) SetExecutionID(v string) *NodeAssignmentUpdate {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableExecutionID(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *NodeAssignmentUpdate) SetNodeID(v string) *NodeAssignmentUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableNodeID(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *NodeAssignmentUpdate) SetPayloadJSON(v string) *NodeAssignmentUpdate {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillablePayloadJSON(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetParentActionID sets the "parent_action_id" field.
func (_u *NodeAssignmentUpdate) SetParentActionID(v string) *NodeAssignmentUpdate {
	_u.mutation.SetParentActionID(v)
	return _u
}

// SetNillableParentActionID sets the "parent_action_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableParentActionID(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetParentActionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeAssignmentUpdate) SetStatus(v string) *NodeAssignmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeAssignmentUpdate) SetNillableStatus(v *string) *NodeAssignmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeAssignmentUpdate) SetUpdatedAt(v time.Time) *NodeAssignmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeAssignmentMutation object of the builder.
func (_u *NodeAssignmentUpdate) Mutation() *NodeAssignmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeAssignmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeAssignmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nodeassignment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeAssignmentUpdate) check() error {
	if v, ok := _u.mutation.WorkflowID(); ok {
		if err := nodeassignment.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.workflow_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := nodeassignment.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := nodeassignment.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.node_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeassignment.Table, nodeassignment.Columns, sqlgraph.NewFieldSpec(nodeassignment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(nodeassignment.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(nodeassignment.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(nodeassignment.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(nodeassignment.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(nodeassignment.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentActionID(); ok {
		_spec.SetField(nodeassignment.FieldParentActionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nodeassignment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nodeassignment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeAssignmentUpdateOne is the builder for updating a single NodeAssignment entity.
type NodeAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeAssignmentMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *NodeAssignmentUpdateOne) SetTenantID(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableTenantID(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *NodeAssignmentUpdateOne) SetWorkflowID(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableWorkflowID(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *NodeAssignmentUpdateOne) SetExecutionID(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableExecutionID(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *NodeAssignmentUpdateOne) SetNodeID(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableNodeID(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *NodeAssignmentUpdateOne) SetPayloadJSON(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillablePayloadJSON(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetParentActionID sets the "parent_action_id" field.
func (_u *NodeAssignmentUpdateOne) SetParentActionID(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetParentActionID(v)
	return _u
}

// SetNillableParentActionID sets the "parent_action_id" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableParentActionID(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetParentActionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeAssignmentUpdateOne) SetStatus(v string) *NodeAssignmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeAssignmentUpdateOne) SetNillableStatus(v *string) *NodeAssignmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeAssignmentUpdateOne) SetUpdatedAt(v time.Time) *NodeAssignmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeAssignmentMutation object of the builder.
func (_u *NodeAssignmentUpdateOne) Mutation() *NodeAssignmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeAssignmentUpdate builder.
func (_u *NodeAssignmentUpdateOne) Where(ps ...predicate.NodeAssignment) *NodeAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeAssignmentUpdateOne) Select(field string, fields ...string) *NodeAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NodeAssignment entity.
func (_u *NodeAssignmentUpdateOne) Save(ctx context.Context) (*NodeAssignment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeAssignmentUpdateOne) SaveX(ctx context.Context) *NodeAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeAssignmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nodeassignment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeAssignmentUpdateOne) check() error {
	if v, ok := _u.mutation.WorkflowID(); ok {
		if err := nodeassignment.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.workflow_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := nodeassignment.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := nodeassignment.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "NodeAssignment.node_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *NodeAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeassignment.Table, nodeassignment.Columns, sqlgraph.NewFieldSpec(nodeassignment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NodeAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodeassignment.FieldID)
		for _, f := range fields {
			if !nodeassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nodeassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(nodeassignment.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(nodeassignment.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(nodeassignment.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(nodeassignment.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(nodeassignment.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentActionID(); ok {
		_spec.SetField(nodeassignment.FieldParentActionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nodeassignment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nodeassignment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NodeAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
