// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/remoteclient"
)

// RemoteClientCreate is the builder for creating a RemoteClient entity.
type RemoteClientCreate struct {
	config
	mutation *RemoteClientMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RemoteClientCreate) SetName(v string) *RemoteClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RemoteClientCreate) SetTenantID(v string) *RemoteClientCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableTenantID(v *string) *RemoteClientCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *RemoteClientCreate) SetTags(v []string) *RemoteClientCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *RemoteClientCreate) SetTokenHash(v string) *RemoteClientCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetRegisteredAt sets the "registered_at" field.
func (_c *RemoteClientCreate) SetRegisteredAt(v time.Time) *RemoteClientCreate {
	_c.mutation.SetRegisteredAt(v)
	return _c
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableRegisteredAt(v *time.Time) *RemoteClientCreate {
	if v != nil {
		_c.SetRegisteredAt(*v)
	}
	return _c
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_c *RemoteClientCreate) SetLastHeartbeat(v time.Time) *RemoteClientCreate {
	_c.mutation.SetLastHeartbeat(v)
	return _c
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableLastHeartbeat(v *time.Time) *RemoteClientCreate {
	if v != nil {
		_c.SetLastHeartbeat(*v)
	}
	return _c
}

// SetLastPoll sets the "last_poll" field.
func (_c *RemoteClientCreate) SetLastPoll(v time.Time) *RemoteClientCreate {
	_c.mutation.SetLastPoll(v)
	return _c
}

// SetNillableLastPoll sets the "last_poll" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableLastPoll(v *time.Time) *RemoteClientCreate {
	if v != nil {
		_c.SetLastPoll(*v)
	}
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *RemoteClientCreate) SetRevoked(v bool) *RemoteClientCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableRevoked(v *bool) *RemoteClientCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *RemoteClientCreate) SetRevokedAt(v time.Time) *RemoteClientCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableRevokedAt(v *time.Time) *RemoteClientCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetDialInfo sets the "dial_info" field.
func (_c *RemoteClientCreate) SetDialInfo(v string) *RemoteClientCreate {
	_c.mutation.SetDialInfo(v)
	return _c
}

// SetNillableDialInfo sets the "dial_info" field if the given value is not nil.
func (_c *RemoteClientCreate) SetNillableDialInfo(v *string) *RemoteClientCreate {
	if v != nil {
		_c.SetDialInfo(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RemoteClientCreate) SetID(v string) *RemoteClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RemoteClientMutation object of the builder.
func (_c *RemoteClientCreate) Mutation() *RemoteClientMutation {
	return _c.mutation
}

// Save creates the RemoteClient in the database.
func (_c *RemoteClientCreate) Save(ctx context.Context) (*RemoteClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemoteClientCreate) SaveX(ctx context.Context) *RemoteClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RemoteClientCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := remoteclient.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		v := remoteclient.DefaultRegisteredAt()
		_c.mutation.SetRegisteredAt(v)
	}
	if _, ok := _c.mutation.LastHeartbeat(); !ok {
		v := remoteclient.DefaultLastHeartbeat()
		_c.mutation.SetLastHeartbeat(v)
	}
	if _, ok := _c.mutation.LastPoll(); !ok {
		v := remoteclient.DefaultLastPoll()
		_c.mutation.SetLastPoll(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := remoteclient.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.DialInfo(); !ok {
		v := remoteclient.DefaultDialInfo
		_c.mutation.SetDialInfo(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemoteClientCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RemoteClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := remoteclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RemoteClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RemoteClient.tenant_id"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "RemoteClient.tags"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "RemoteClient.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := remoteclient.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "RemoteClient.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		return &ValidationError{Name: "registered_at", err: errors.New(`ent: missing required field "RemoteClient.registered_at"`)}
	}
	if _, ok := _c.mutation.LastHeartbeat(); !ok {
		return &ValidationError{Name: "last_heartbeat", err: errors.New(`ent: missing required field "RemoteClient.last_heartbeat"`)}
	}
	if _, ok := _c.mutation.LastPoll(); !ok {
		return &ValidationError{Name: "last_poll", err: errors.New(`ent: missing required field "RemoteClient.last_poll"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "RemoteClient.revoked"`)}
	}
	if _, ok := _c.mutation.DialInfo(); !ok {
		return &ValidationError{Name: "dial_info", err: errors.New(`ent: missing required field "RemoteClient.dial_info"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := remoteclient.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RemoteClient.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RemoteClientCreate) sqlSave(ctx context.Context) (*RemoteClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RemoteClient.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemoteClientCreate) createSpec() (*RemoteClient, *sqlgraph.CreateSpec) {
	var (
		_node = &RemoteClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remoteclient.Table, sqlgraph.NewFieldSpec(remoteclient.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(remoteclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(remoteclient.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(remoteclient.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(remoteclient.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.RegisteredAt(); ok {
		_spec.SetField(remoteclient.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	if value, ok := _c.mutation.LastHeartbeat(); ok {
		_spec.SetField(remoteclient.FieldLastHeartbeat, field.TypeTime, value)
		_node.LastHeartbeat = value
	}
	if value, ok := _c.mutation.LastPoll(); ok {
		_spec.SetField(remoteclient.FieldLastPoll, field.TypeTime, value)
		_node.LastPoll = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(remoteclient.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(remoteclient.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.DialInfo(); ok {
		_spec.SetField(remoteclient.FieldDialInfo, field.TypeString, value)
		_node.DialInfo = value
	}
	return _node, _spec
}

// RemoteClientCreateBulk is the builder for creating many RemoteClient entities in bulk.
type RemoteClientCreateBulk struct {
	config
	err      error
	builders []*RemoteClientCreate
}

// Save creates the RemoteClient entities in the database.
func (_c *RemoteClientCreateBulk) Save(ctx context.Context) ([]*RemoteClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemoteClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemoteClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemoteClientCreateBulk) SaveX(ctx context.Context) []*RemoteClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
