// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mcmx/nitejaguar/ent/appuser"
	"github.com/mcmx/nitejaguar/ent/auditlog"
	"github.com/mcmx/nitejaguar/ent/authsession"
	"github.com/mcmx/nitejaguar/ent/credential"
	"github.com/mcmx/nitejaguar/ent/enrollmenttoken"
	"github.com/mcmx/nitejaguar/ent/nodeassignment"
	"github.com/mcmx/nitejaguar/ent/remoteclient"
	"github.com/mcmx/nitejaguar/ent/schema"
	"github.com/mcmx/nitejaguar/ent/transferchunk"
	"github.com/mcmx/nitejaguar/ent/transfersession"
	"github.com/mcmx/nitejaguar/ent/transfersignal"
	"github.com/mcmx/nitejaguar/ent/workflow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appuserFields := schema.AppUser{}.Fields()
	_ = appuserFields
	// appuserDescTenantID is the schema descriptor for tenant_id field.
	appuserDescTenantID := appuserFields[1].Descriptor()
	// appuser.DefaultTenantID holds the default value on creation for the tenant_id field.
	appuser.DefaultTenantID = appuserDescTenantID.Default.(string)
	// appuserDescUsername is the schema descriptor for username field.
	appuserDescUsername := appuserFields[2].Descriptor()
	// appuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	appuser.UsernameValidator = appuserDescUsername.Validators[0].(func(string) error)
	// appuserDescPasswordHash is the schema descriptor for password_hash field.
	appuserDescPasswordHash := appuserFields[3].Descriptor()
	// appuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	appuser.PasswordHashValidator = appuserDescPasswordHash.Validators[0].(func(string) error)
	// appuserDescRole is the schema descriptor for role field.
	appuserDescRole := appuserFields[4].Descriptor()
	// appuser.DefaultRole holds the default value on creation for the role field.
	appuser.DefaultRole = appuserDescRole.Default.(string)
	// appuserDescRevoked is the schema descriptor for revoked field.
	appuserDescRevoked := appuserFields[6].Descriptor()
	// appuser.DefaultRevoked holds the default value on creation for the revoked field.
	appuser.DefaultRevoked = appuserDescRevoked.Default.(bool)
	// appuserDescCreatedAt is the schema descriptor for created_at field.
	appuserDescCreatedAt := appuserFields[7].Descriptor()
	// appuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	appuser.DefaultCreatedAt = appuserDescCreatedAt.Default.(func() time.Time)
	// appuserDescUpdatedAt is the schema descriptor for updated_at field.
	appuserDescUpdatedAt := appuserFields[8].Descriptor()
	// appuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appuser.DefaultUpdatedAt = appuserDescUpdatedAt.Default.(func() time.Time)
	// appuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appuser.UpdateDefaultUpdatedAt = appuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appuserDescID is the schema descriptor for id field.
	appuserDescID := appuserFields[0].Descriptor()
	// appuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	appuser.IDValidator = appuserDescID.Validators[0].(func(string) error)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescTenantID is the schema descriptor for tenant_id field.
	auditlogDescTenantID := auditlogFields[2].Descriptor()
	// auditlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	auditlog.DefaultTenantID = auditlogDescTenantID.Default.(string)
	// auditlogDescActor is the schema descriptor for actor field.
	auditlogDescActor := auditlogFields[3].Descriptor()
	// auditlog.DefaultActor holds the default value on creation for the actor field.
	auditlog.DefaultActor = auditlogDescActor.Default.(string)
	// auditlogDescTarget is the schema descriptor for target field.
	auditlogDescTarget := auditlogFields[4].Descriptor()
	// auditlog.DefaultTarget holds the default value on creation for the target field.
	auditlog.DefaultTarget = auditlogDescTarget.Default.(string)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[5].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[6].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditlog.IDValidator = auditlogDescID.Validators[0].(func(string) error)
	authsessionFields := schema.AuthSession{}.Fields()
	_ = authsessionFields
	// authsessionDescUserID is the schema descriptor for user_id field.
	authsessionDescUserID := authsessionFields[1].Descriptor()
	// authsession.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	authsession.UserIDValidator = authsessionDescUserID.Validators[0].(func(string) error)
	// authsessionDescTenantID is the schema descriptor for tenant_id field.
	authsessionDescTenantID := authsessionFields[2].Descriptor()
	// authsession.DefaultTenantID holds the default value on creation for the tenant_id field.
	authsession.DefaultTenantID = authsessionDescTenantID.Default.(string)
	// authsessionDescTokenHash is the schema descriptor for token_hash field.
	authsessionDescTokenHash := authsessionFields[3].Descriptor()
	// authsession.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	authsession.TokenHashValidator = authsessionDescTokenHash.Validators[0].(func(string) error)
	// authsessionDescRevoked is the schema descriptor for revoked field.
	authsessionDescRevoked := authsessionFields[5].Descriptor()
	// authsession.DefaultRevoked holds the default value on creation for the revoked field.
	authsession.DefaultRevoked = authsessionDescRevoked.Default.(bool)
	// authsessionDescCreatedAt is the schema descriptor for created_at field.
	authsessionDescCreatedAt := authsessionFields[6].Descriptor()
	// authsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	authsession.DefaultCreatedAt = authsessionDescCreatedAt.Default.(func() time.Time)
	// authsessionDescID is the schema descriptor for id field.
	authsessionDescID := authsessionFields[0].Descriptor()
	// authsession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authsession.IDValidator = authsessionDescID.Validators[0].(func(string) error)
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescTenantID is the schema descriptor for tenant_id field.
	credentialDescTenantID := credentialFields[1].Descriptor()
	// credential.DefaultTenantID holds the default value on creation for the tenant_id field.
	credential.DefaultTenantID = credentialDescTenantID.Default.(string)
	// credentialDescName is the schema descriptor for name field.
	credentialDescName := credentialFields[2].Descriptor()
	// credential.NameValidator is a validator for the "name" field. It is called by the builders before save.
	credential.NameValidator = credentialDescName.Validators[0].(func(string) error)
	// credentialDescType is the schema descriptor for type field.
	credentialDescType := credentialFields[3].Descriptor()
	// credential.DefaultType holds the default value on creation for the type field.
	credential.DefaultType = credentialDescType.Default.(string)
	// credentialDescScope is the schema descriptor for scope field.
	credentialDescScope := credentialFields[4].Descriptor()
	// credential.DefaultScope holds the default value on creation for the scope field.
	credential.DefaultScope = credentialDescScope.Default.(string)
	// credentialDescOwnerID is the schema descriptor for owner_id field.
	credentialDescOwnerID := credentialFields[5].Descriptor()
	// credential.DefaultOwnerID holds the default value on creation for the owner_id field.
	credential.DefaultOwnerID = credentialDescOwnerID.Default.(string)
	// credentialDescSecretEncrypted is the schema descriptor for secret_encrypted field.
	credentialDescSecretEncrypted := credentialFields[6].Descriptor()
	// credential.SecretEncryptedValidator is a validator for the "secret_encrypted" field. It is called by the builders before save.
	credential.SecretEncryptedValidator = credentialDescSecretEncrypted.Validators[0].(func(string) error)
	// credentialDescDescription is the schema descriptor for description field.
	credentialDescDescription := credentialFields[7].Descriptor()
	// credential.DefaultDescription holds the default value on creation for the description field.
	credential.DefaultDescription = credentialDescDescription.Default.(string)
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[8].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[9].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	// credential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	credential.UpdateDefaultUpdatedAt = credentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// credentialDescID is the schema descriptor for id field.
	credentialDescID := credentialFields[0].Descriptor()
	// credential.IDValidator is a validator for the "id" field. It is called by the builders before save.
	credential.IDValidator = credentialDescID.Validators[0].(func(string) error)
	enrollmenttokenFields := schema.EnrollmentToken{}.Fields()
	_ = enrollmenttokenFields
	// enrollmenttokenDescTenantID is the schema descriptor for tenant_id field.
	enrollmenttokenDescTenantID := enrollmenttokenFields[1].Descriptor()
	// enrollmenttoken.DefaultTenantID holds the default value on creation for the tenant_id field.
	enrollmenttoken.DefaultTenantID = enrollmenttokenDescTenantID.Default.(string)
	// enrollmenttokenDescLabel is the schema descriptor for label field.
	enrollmenttokenDescLabel := enrollmenttokenFields[2].Descriptor()
	// enrollmenttoken.DefaultLabel holds the default value on creation for the label field.
	enrollmenttoken.DefaultLabel = enrollmenttokenDescLabel.Default.(string)
	// enrollmenttokenDescTokenHash is the schema descriptor for token_hash field.
	enrollmenttokenDescTokenHash := enrollmenttokenFields[3].Descriptor()
	// enrollmenttoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	enrollmenttoken.TokenHashValidator = enrollmenttokenDescTokenHash.Validators[0].(func(string) error)
	// enrollmenttokenDescMaxUses is the schema descriptor for max_uses field.
	enrollmenttokenDescMaxUses := enrollmenttokenFields[5].Descriptor()
	// enrollmenttoken.DefaultMaxUses holds the default value on creation for the max_uses field.
	enrollmenttoken.DefaultMaxUses = enrollmenttokenDescMaxUses.Default.(int)
	// enrollmenttokenDescUseCount is the schema descriptor for use_count field.
	enrollmenttokenDescUseCount := enrollmenttokenFields[6].Descriptor()
	// enrollmenttoken.DefaultUseCount holds the default value on creation for the use_count field.
	enrollmenttoken.DefaultUseCount = enrollmenttokenDescUseCount.Default.(int)
	// enrollmenttokenDescRevoked is the schema descriptor for revoked field.
	enrollmenttokenDescRevoked := enrollmenttokenFields[7].Descriptor()
	// enrollmenttoken.DefaultRevoked holds the default value on creation for the revoked field.
	enrollmenttoken.DefaultRevoked = enrollmenttokenDescRevoked.Default.(bool)
	// enrollmenttokenDescCreatedAt is the schema descriptor for created_at field.
	enrollmenttokenDescCreatedAt := enrollmenttokenFields[8].Descriptor()
	// enrollmenttoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	enrollmenttoken.DefaultCreatedAt = enrollmenttokenDescCreatedAt.Default.(func() time.Time)
	// enrollmenttokenDescID is the schema descriptor for id field.
	enrollmenttokenDescID := enrollmenttokenFields[0].Descriptor()
	// enrollmenttoken.IDValidator is a validator for the "id" field. It is called by the builders before save.
	enrollmenttoken.IDValidator = enrollmenttokenDescID.Validators[0].(func(string) error)
	nodeassignmentFields := schema.NodeAssignment{}.Fields()
	_ = nodeassignmentFields
	// nodeassignmentDescTenantID is the schema descriptor for tenant_id field.
	nodeassignmentDescTenantID := nodeassignmentFields[1].Descriptor()
	// nodeassignment.DefaultTenantID holds the default value on creation for the tenant_id field.
	nodeassignment.DefaultTenantID = nodeassignmentDescTenantID.Default.(string)
	// nodeassignmentDescWorkflowID is the schema descriptor for workflow_id field.
	nodeassignmentDescWorkflowID := nodeassignmentFields[2].Descriptor()
	// nodeassignment.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	nodeassignment.WorkflowIDValidator = nodeassignmentDescWorkflowID.Validators[0].(func(string) error)
	// nodeassignmentDescExecutionID is the schema descriptor for execution_id field.
	nodeassignmentDescExecutionID := nodeassignmentFields[3].Descriptor()
	// nodeassignment.ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	nodeassignment.ExecutionIDValidator = nodeassignmentDescExecutionID.Validators[0].(func(string) error)
	// nodeassignmentDescNodeID is the schema descriptor for node_id field.
	nodeassignmentDescNodeID := nodeassignmentFields[4].Descriptor()
	// nodeassignment.NodeIDValidator is a validator for the "node_id" field. It is called by the builders before save.
	nodeassignment.NodeIDValidator = nodeassignmentDescNodeID.Validators[0].(func(string) error)
	// nodeassignmentDescPayloadJSON is the schema descriptor for payload_json field.
	nodeassignmentDescPayloadJSON := nodeassignmentFields[5].Descriptor()
	// nodeassignment.DefaultPayloadJSON holds the default value on creation for the payload_json field.
	nodeassignment.DefaultPayloadJSON = nodeassignmentDescPayloadJSON.Default.(string)
	// nodeassignmentDescParentActionID is the schema descriptor for parent_action_id field.
	nodeassignmentDescParentActionID := nodeassignmentFields[6].Descriptor()
	// nodeassignment.DefaultParentActionID holds the default value on creation for the parent_action_id field.
	nodeassignment.DefaultParentActionID = nodeassignmentDescParentActionID.Default.(string)
	// nodeassignmentDescStatus is the schema descriptor for status field.
	nodeassignmentDescStatus := nodeassignmentFields[7].Descriptor()
	// nodeassignment.DefaultStatus holds the default value on creation for the status field.
	nodeassignment.DefaultStatus = nodeassignmentDescStatus.Default.(string)
	// nodeassignmentDescCreatedAt is the schema descriptor for created_at field.
	nodeassignmentDescCreatedAt := nodeassignmentFields[8].Descriptor()
	// nodeassignment.DefaultCreatedAt holds the default value on creation for the created_at field.
	nodeassignment.DefaultCreatedAt = nodeassignmentDescCreatedAt.Default.(func() time.Time)
	// nodeassignmentDescUpdatedAt is the schema descriptor for updated_at field.
	nodeassignmentDescUpdatedAt := nodeassignmentFields[9].Descriptor()
	// nodeassignment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	nodeassignment.DefaultUpdatedAt = nodeassignmentDescUpdatedAt.Default.(func() time.Time)
	// nodeassignment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	nodeassignment.UpdateDefaultUpdatedAt = nodeassignmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeassignmentDescID is the schema descriptor for id field.
	nodeassignmentDescID := nodeassignmentFields[0].Descriptor()
	// nodeassignment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	nodeassignment.IDValidator = nodeassignmentDescID.Validators[0].(func(string) error)
	remoteclientFields := schema.RemoteClient{}.Fields()
	_ = remoteclientFields
	// remoteclientDescName is the schema descriptor for name field.
	remoteclientDescName := remoteclientFields[1].Descriptor()
	// remoteclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	remoteclient.NameValidator = remoteclientDescName.Validators[0].(func(string) error)
	// remoteclientDescTenantID is the schema descriptor for tenant_id field.
	remoteclientDescTenantID := remoteclientFields[2].Descriptor()
	// remoteclient.DefaultTenantID holds the default value on creation for the tenant_id field.
	remoteclient.DefaultTenantID = remoteclientDescTenantID.Default.(string)
	// remoteclientDescTokenHash is the schema descriptor for token_hash field.
	remoteclientDescTokenHash := remoteclientFields[4].Descriptor()
	// remoteclient.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	remoteclient.TokenHashValidator = remoteclientDescTokenHash.Validators[0].(func(string) error)
	// remoteclientDescRegisteredAt is the schema descriptor for registered_at field.
	remoteclientDescRegisteredAt := remoteclientFields[5].Descriptor()
	// remoteclient.DefaultRegisteredAt holds the default value on creation for the registered_at field.
	remoteclient.DefaultRegisteredAt = remoteclientDescRegisteredAt.Default.(func() time.Time)
	// remoteclientDescLastHeartbeat is the schema descriptor for last_heartbeat field.
	remoteclientDescLastHeartbeat := remoteclientFields[6].Descriptor()
	// remoteclient.DefaultLastHeartbeat holds the default value on creation for the last_heartbeat field.
	remoteclient.DefaultLastHeartbeat = remoteclientDescLastHeartbeat.Default.(func() time.Time)
	// remoteclient.UpdateDefaultLastHeartbeat holds the default value on update for the last_heartbeat field.
	remoteclient.UpdateDefaultLastHeartbeat = remoteclientDescLastHeartbeat.UpdateDefault.(func() time.Time)
	// remoteclientDescLastPoll is the schema descriptor for last_poll field.
	remoteclientDescLastPoll := remoteclientFields[7].Descriptor()
	// remoteclient.DefaultLastPoll holds the default value on creation for the last_poll field.
	remoteclient.DefaultLastPoll = remoteclientDescLastPoll.Default.(func() time.Time)
	// remoteclient.UpdateDefaultLastPoll holds the default value on update for the last_poll field.
	remoteclient.UpdateDefaultLastPoll = remoteclientDescLastPoll.UpdateDefault.(func() time.Time)
	// remoteclientDescRevoked is the schema descriptor for revoked field.
	remoteclientDescRevoked := remoteclientFields[8].Descriptor()
	// remoteclient.DefaultRevoked holds the default value on creation for the revoked field.
	remoteclient.DefaultRevoked = remoteclientDescRevoked.Default.(bool)
	// remoteclientDescDialInfo is the schema descriptor for dial_info field.
	remoteclientDescDialInfo := remoteclientFields[10].Descriptor()
	// remoteclient.DefaultDialInfo holds the default value on creation for the dial_info field.
	remoteclient.DefaultDialInfo = remoteclientDescDialInfo.Default.(string)
	// remoteclientDescID is the schema descriptor for id field.
	remoteclientDescID := remoteclientFields[0].Descriptor()
	// remoteclient.IDValidator is a validator for the "id" field. It is called by the builders before save.
	remoteclient.IDValidator = remoteclientDescID.Validators[0].(func(string) error)
	transferchunkFields := schema.TransferChunk{}.Fields()
	_ = transferchunkFields
	// transferchunkDescTransferID is the schema descriptor for transfer_id field.
	transferchunkDescTransferID := transferchunkFields[1].Descriptor()
	// transferchunk.TransferIDValidator is a validator for the "transfer_id" field. It is called by the builders before save.
	transferchunk.TransferIDValidator = transferchunkDescTransferID.Validators[0].(func(string) error)
	// transferchunkDescSeq is the schema descriptor for seq field.
	transferchunkDescSeq := transferchunkFields[2].Descriptor()
	// transferchunk.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	transferchunk.SeqValidator = transferchunkDescSeq.Validators[0].(func(int) error)
	// transferchunkDescData is the schema descriptor for data field.
	transferchunkDescData := transferchunkFields[3].Descriptor()
	// transferchunk.DataValidator is a validator for the "data" field. It is called by the builders before save.
	transferchunk.DataValidator = transferchunkDescData.Validators[0].(func([]byte) error)
	// transferchunkDescCreatedAt is the schema descriptor for created_at field.
	transferchunkDescCreatedAt := transferchunkFields[4].Descriptor()
	// transferchunk.DefaultCreatedAt holds the default value on creation for the created_at field.
	transferchunk.DefaultCreatedAt = transferchunkDescCreatedAt.Default.(func() time.Time)
	// transferchunkDescID is the schema descriptor for id field.
	transferchunkDescID := transferchunkFields[0].Descriptor()
	// transferchunk.IDValidator is a validator for the "id" field. It is called by the builders before save.
	transferchunk.IDValidator = transferchunkDescID.Validators[0].(func(string) error)
	transfersessionFields := schema.TransferSession{}.Fields()
	_ = transfersessionFields
	// transfersessionDescTenantID is the schema descriptor for tenant_id field.
	transfersessionDescTenantID := transfersessionFields[1].Descriptor()
	// transfersession.DefaultTenantID holds the default value on creation for the tenant_id field.
	transfersession.DefaultTenantID = transfersessionDescTenantID.Default.(string)
	// transfersessionDescWorkflowID is the schema descriptor for workflow_id field.
	transfersessionDescWorkflowID := transfersessionFields[2].Descriptor()
	// transfersession.DefaultWorkflowID holds the default value on creation for the workflow_id field.
	transfersession.DefaultWorkflowID = transfersessionDescWorkflowID.Default.(string)
	// transfersessionDescExecutionID is the schema descriptor for execution_id field.
	transfersessionDescExecutionID := transfersessionFields[3].Descriptor()
	// transfersession.DefaultExecutionID holds the default value on creation for the execution_id field.
	transfersession.DefaultExecutionID = transfersessionDescExecutionID.Default.(string)
	// transfersessionDescNodeID is the schema descriptor for node_id field.
	transfersessionDescNodeID := transfersessionFields[4].Descriptor()
	// transfersession.DefaultNodeID holds the default value on creation for the node_id field.
	transfersession.DefaultNodeID = transfersessionDescNodeID.Default.(string)
	// transfersessionDescSenderClientID is the schema descriptor for sender_client_id field.
	transfersessionDescSenderClientID := transfersessionFields[5].Descriptor()
	// transfersession.SenderClientIDValidator is a validator for the "sender_client_id" field. It is called by the builders before save.
	transfersession.SenderClientIDValidator = transfersessionDescSenderClientID.Validators[0].(func(string) error)
	// transfersessionDescReceiverClientID is the schema descriptor for receiver_client_id field.
	transfersessionDescReceiverClientID := transfersessionFields[6].Descriptor()
	// transfersession.DefaultReceiverClientID holds the default value on creation for the receiver_client_id field.
	transfersession.DefaultReceiverClientID = transfersessionDescReceiverClientID.Default.(string)
	// transfersessionDescFileName is the schema descriptor for file_name field.
	transfersessionDescFileName := transfersessionFields[8].Descriptor()
	// transfersession.DefaultFileName holds the default value on creation for the file_name field.
	transfersession.DefaultFileName = transfersessionDescFileName.Default.(string)
	// transfersessionDescDestinationFile is the schema descriptor for destination_file field.
	transfersessionDescDestinationFile := transfersessionFields[9].Descriptor()
	// transfersession.DestinationFileValidator is a validator for the "destination_file" field. It is called by the builders before save.
	transfersession.DestinationFileValidator = transfersessionDescDestinationFile.Validators[0].(func(string) error)
	// transfersessionDescPermissions is the schema descriptor for permissions field.
	transfersessionDescPermissions := transfersessionFields[10].Descriptor()
	// transfersession.DefaultPermissions holds the default value on creation for the permissions field.
	transfersession.DefaultPermissions = transfersessionDescPermissions.Default.(string)
	// transfersessionDescSize is the schema descriptor for size field.
	transfersessionDescSize := transfersessionFields[11].Descriptor()
	// transfersession.DefaultSize holds the default value on creation for the size field.
	transfersession.DefaultSize = transfersessionDescSize.Default.(int64)
	// transfersessionDescSha256 is the schema descriptor for sha256 field.
	transfersessionDescSha256 := transfersessionFields[12].Descriptor()
	// transfersession.DefaultSha256 holds the default value on creation for the sha256 field.
	transfersession.DefaultSha256 = transfersessionDescSha256.Default.(string)
	// transfersessionDescStatus is the schema descriptor for status field.
	transfersessionDescStatus := transfersessionFields[13].Descriptor()
	// transfersession.DefaultStatus holds the default value on creation for the status field.
	transfersession.DefaultStatus = transfersessionDescStatus.Default.(string)
	// transfersessionDescViaP2p is the schema descriptor for via_p2p field.
	transfersessionDescViaP2p := transfersessionFields[14].Descriptor()
	// transfersession.DefaultViaP2p holds the default value on creation for the via_p2p field.
	transfersession.DefaultViaP2p = transfersessionDescViaP2p.Default.(bool)
	// transfersessionDescCreatedAt is the schema descriptor for created_at field.
	transfersessionDescCreatedAt := transfersessionFields[15].Descriptor()
	// transfersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	transfersession.DefaultCreatedAt = transfersessionDescCreatedAt.Default.(func() time.Time)
	// transfersessionDescUpdatedAt is the schema descriptor for updated_at field.
	transfersessionDescUpdatedAt := transfersessionFields[16].Descriptor()
	// transfersession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transfersession.DefaultUpdatedAt = transfersessionDescUpdatedAt.Default.(func() time.Time)
	// transfersession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transfersession.UpdateDefaultUpdatedAt = transfersessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// transfersessionDescID is the schema descriptor for id field.
	transfersessionDescID := transfersessionFields[0].Descriptor()
	// transfersession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	transfersession.IDValidator = transfersessionDescID.Validators[0].(func(string) error)
	transfersignalFields := schema.TransferSignal{}.Fields()
	_ = transfersignalFields
	// transfersignalDescTransferID is the schema descriptor for transfer_id field.
	transfersignalDescTransferID := transfersignalFields[1].Descriptor()
	// transfersignal.TransferIDValidator is a validator for the "transfer_id" field. It is called by the builders before save.
	transfersignal.TransferIDValidator = transfersignalDescTransferID.Validators[0].(func(string) error)
	// transfersignalDescFromClientID is the schema descriptor for from_client_id field.
	transfersignalDescFromClientID := transfersignalFields[2].Descriptor()
	// transfersignal.FromClientIDValidator is a validator for the "from_client_id" field. It is called by the builders before save.
	transfersignal.FromClientIDValidator = transfersignalDescFromClientID.Validators[0].(func(string) error)
	// transfersignalDescKind is the schema descriptor for kind field.
	transfersignalDescKind := transfersignalFields[3].Descriptor()
	// transfersignal.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	transfersignal.KindValidator = transfersignalDescKind.Validators[0].(func(string) error)
	// transfersignalDescPayload is the schema descriptor for payload field.
	transfersignalDescPayload := transfersignalFields[4].Descriptor()
	// transfersignal.DefaultPayload holds the default value on creation for the payload field.
	transfersignal.DefaultPayload = transfersignalDescPayload.Default.(string)
	// transfersignalDescCreatedAt is the schema descriptor for created_at field.
	transfersignalDescCreatedAt := transfersignalFields[5].Descriptor()
	// transfersignal.DefaultCreatedAt holds the default value on creation for the created_at field.
	transfersignal.DefaultCreatedAt = transfersignalDescCreatedAt.Default.(func() time.Time)
	// transfersignalDescID is the schema descriptor for id field.
	transfersignalDescID := transfersignalFields[0].Descriptor()
	// transfersignal.IDValidator is a validator for the "id" field. It is called by the builders before save.
	transfersignal.IDValidator = transfersignalDescID.Validators[0].(func(string) error)
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescEnabled is the schema descriptor for enabled field.
	workflowDescEnabled := workflowFields[1].Descriptor()
	// workflow.DefaultEnabled holds the default value on creation for the enabled field.
	workflow.DefaultEnabled = workflowDescEnabled.Default.(bool)
	// workflowDescTenantID is the schema descriptor for tenant_id field.
	workflowDescTenantID := workflowFields[2].Descriptor()
	// workflow.DefaultTenantID holds the default value on creation for the tenant_id field.
	workflow.DefaultTenantID = workflowDescTenantID.Default.(string)
	// workflowDescRevision is the schema descriptor for revision field.
	workflowDescRevision := workflowFields[3].Descriptor()
	// workflow.DefaultRevision holds the default value on creation for the revision field.
	workflow.DefaultRevision = workflowDescRevision.Default.(string)
	// workflow.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	workflow.RevisionValidator = workflowDescRevision.Validators[0].(func(string) error)
	// workflowDescJSONDefinition is the schema descriptor for json_definition field.
	workflowDescJSONDefinition := workflowFields[4].Descriptor()
	// workflow.JSONDefinitionValidator is a validator for the "json_definition" field. It is called by the builders before save.
	workflow.JSONDefinitionValidator = workflowDescJSONDefinition.Validators[0].(func(string) error)
	// workflowDescCreatedAt is the schema descriptor for created_at field.
	workflowDescCreatedAt := workflowFields[5].Descriptor()
	// workflow.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflow.DefaultCreatedAt = workflowDescCreatedAt.Default.(func() time.Time)
	// workflowDescUpdatedAt is the schema descriptor for updated_at field.
	workflowDescUpdatedAt := workflowFields[6].Descriptor()
	// workflow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflow.DefaultUpdatedAt = workflowDescUpdatedAt.Default.(func() time.Time)
	// workflow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workflow.UpdateDefaultUpdatedAt = workflowDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workflowDescID is the schema descriptor for id field.
	workflowDescID := workflowFields[0].Descriptor()
	// workflow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workflow.IDValidator = workflowDescID.Validators[0].(func(string) error)
}
