// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mcmx/nitejaguar/ent/remoteclient"
	"github.com/mcmx/nitejaguar/ent/schema"
	"github.com/mcmx/nitejaguar/ent/workflow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	remoteclientFields := schema.RemoteClient{}.Fields()
	_ = remoteclientFields
	// remoteclientDescName is the schema descriptor for name field.
	remoteclientDescName := remoteclientFields[1].Descriptor()
	// remoteclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	remoteclient.NameValidator = remoteclientDescName.Validators[0].(func(string) error)
	// remoteclientDescTenantID is the schema descriptor for tenant_id field.
	remoteclientDescTenantID := remoteclientFields[2].Descriptor()
	// remoteclient.DefaultTenantID holds the default value on creation for the tenant_id field.
	remoteclient.DefaultTenantID = remoteclientDescTenantID.Default.(string)
	// remoteclientDescTokenHash is the schema descriptor for token_hash field.
	remoteclientDescTokenHash := remoteclientFields[4].Descriptor()
	// remoteclient.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	remoteclient.TokenHashValidator = remoteclientDescTokenHash.Validators[0].(func(string) error)
	// remoteclientDescRegisteredAt is the schema descriptor for registered_at field.
	remoteclientDescRegisteredAt := remoteclientFields[5].Descriptor()
	// remoteclient.DefaultRegisteredAt holds the default value on creation for the registered_at field.
	remoteclient.DefaultRegisteredAt = remoteclientDescRegisteredAt.Default.(func() time.Time)
	// remoteclientDescLastHeartbeat is the schema descriptor for last_heartbeat field.
	remoteclientDescLastHeartbeat := remoteclientFields[6].Descriptor()
	// remoteclient.DefaultLastHeartbeat holds the default value on creation for the last_heartbeat field.
	remoteclient.DefaultLastHeartbeat = remoteclientDescLastHeartbeat.Default.(func() time.Time)
	// remoteclient.UpdateDefaultLastHeartbeat holds the default value on update for the last_heartbeat field.
	remoteclient.UpdateDefaultLastHeartbeat = remoteclientDescLastHeartbeat.UpdateDefault.(func() time.Time)
	// remoteclientDescLastPoll is the schema descriptor for last_poll field.
	remoteclientDescLastPoll := remoteclientFields[7].Descriptor()
	// remoteclient.DefaultLastPoll holds the default value on creation for the last_poll field.
	remoteclient.DefaultLastPoll = remoteclientDescLastPoll.Default.(func() time.Time)
	// remoteclient.UpdateDefaultLastPoll holds the default value on update for the last_poll field.
	remoteclient.UpdateDefaultLastPoll = remoteclientDescLastPoll.UpdateDefault.(func() time.Time)
	// remoteclientDescID is the schema descriptor for id field.
	remoteclientDescID := remoteclientFields[0].Descriptor()
	// remoteclient.IDValidator is a validator for the "id" field. It is called by the builders before save.
	remoteclient.IDValidator = remoteclientDescID.Validators[0].(func(string) error)
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescEnabled is the schema descriptor for enabled field.
	workflowDescEnabled := workflowFields[1].Descriptor()
	// workflow.DefaultEnabled holds the default value on creation for the enabled field.
	workflow.DefaultEnabled = workflowDescEnabled.Default.(bool)
	// workflowDescTenantID is the schema descriptor for tenant_id field.
	workflowDescTenantID := workflowFields[2].Descriptor()
	// workflow.DefaultTenantID holds the default value on creation for the tenant_id field.
	workflow.DefaultTenantID = workflowDescTenantID.Default.(string)
	// workflowDescJSONDefinition is the schema descriptor for json_definition field.
	workflowDescJSONDefinition := workflowFields[3].Descriptor()
	// workflow.JSONDefinitionValidator is a validator for the "json_definition" field. It is called by the builders before save.
	workflow.JSONDefinitionValidator = workflowDescJSONDefinition.Validators[0].(func(string) error)
	// workflowDescCreatedAt is the schema descriptor for created_at field.
	workflowDescCreatedAt := workflowFields[4].Descriptor()
	// workflow.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflow.DefaultCreatedAt = workflowDescCreatedAt.Default.(func() time.Time)
	// workflowDescUpdatedAt is the schema descriptor for updated_at field.
	workflowDescUpdatedAt := workflowFields[5].Descriptor()
	// workflow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflow.DefaultUpdatedAt = workflowDescUpdatedAt.Default.(func() time.Time)
	// workflow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workflow.UpdateDefaultUpdatedAt = workflowDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workflowDescID is the schema descriptor for id field.
	workflowDescID := workflowFields[0].Descriptor()
	// workflow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workflow.IDValidator = workflowDescID.Validators[0].(func(string) error)
}
