// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/predicate"
	"github.com/mcmx/nitejaguar/ent/transferchunk"
)

// TransferChunkUpdate is the builder for updating TransferChunk entities.
type TransferChunkUpdate struct {
	config
	hooks    []Hook
	mutation *TransferChunkMutation
}

// Where appends a list predicates to the TransferChunkUpdate builder.
func (_u *TransferChunkUpdate) Where(ps ...predicate.TransferChunk) *TransferChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTransferID sets the "transfer_id" field.
func (_u *TransferChunkUpdate) SetTransferID(v string) *TransferChunkUpdate {
	_u.mutation.SetTransferID(v)
	return _u
}

// SetNillableTransferID sets the "transfer_id" field if the given value is not nil.
func (_u *TransferChunkUpdate) SetNillableTransferID(v *string) *TransferChunkUpdate {
	if v != nil {
		_u.SetTransferID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *TransferChunkUpdate) SetSeq(v int) *TransferChunkUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *TransferChunkUpdate) SetNillableSeq(v *int) *TransferChunkUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *TransferChunkUpdate) AddSeq(v int) *TransferChunkUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetData sets the "data" field.
func (_u *TransferChunkUpdate) SetData(v []byte) *TransferChunkUpdate {
	_u.mutation.SetData(v)
	return _u
}

// Mutation returns the TransferChunkMutation object of the builder.
func (_u *TransferChunkUpdate) Mutation() *TransferChunkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransferChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransferChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferChunkUpdate) check() error {
	if v, ok := _u.mutation.TransferID(); ok {
		if err := transferchunk.TransferIDValidator(v); err != nil {
			return &ValidationError{Name: "transfer_id", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.transfer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Seq(); ok {
		if err := transferchunk.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := transferchunk.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.data": %w`, err)}
		}
	}
	return nil
}

func (_u *TransferChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferchunk.Table, transferchunk.Columns, sqlgraph.NewFieldSpec(transferchunk.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TransferID(); ok {
		_spec.SetField(transferchunk.FieldTransferID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(transferchunk.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(transferchunk.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(transferchunk.FieldData, field.TypeBytes, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransferChunkUpdateOne is the builder for updating a single TransferChunk entity.
type TransferChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransferChunkMutation
}

// SetTransferID sets the "transfer_id" field.
func (_u *TransferChunkUpdateOne) SetTransferID(v string) *TransferChunkUpdateOne {
	_u.mutation.SetTransferID(v)
	return _u
}

// SetNillableTransferID sets the "transfer_id" field if the given value is not nil.
func (_u *TransferChunkUpdateOne) SetNillableTransferID(v *string) *TransferChunkUpdateOne {
	if v != nil {
		_u.SetTransferID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *TransferChunkUpdateOne) SetSeq(v int) *TransferChunkUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *TransferChunkUpdateOne) SetNillableSeq(v *int) *TransferChunkUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *TransferChunkUpdateOne) AddSeq(v int) *TransferChunkUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetData sets the "data" field.
func (_u *TransferChunkUpdateOne) SetData(v []byte) *TransferChunkUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// Mutation returns the TransferChunkMutation object of the builder.
func (_u *TransferChunkUpdateOne) Mutation() *TransferChunkMutation {
	return _u.mutation
}

// Where appends a list predicates to the TransferChunkUpdate builder.
func (_u *TransferChunkUpdateOne) Where(ps ...predicate.TransferChunk) *TransferChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransferChunkUpdateOne) Select(field string, fields ...string) *TransferChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransferChunk entity.
func (_u *TransferChunkUpdateOne) Save(ctx context.Context) (*TransferChunk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferChunkUpdateOne) SaveX(ctx context.Context) *TransferChunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransferChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferChunkUpdateOne) check() error {
	if v, ok := _u.mutation.TransferID(); ok {
		if err := transferchunk.TransferIDValidator(v); err != nil {
			return &ValidationError{Name: "transfer_id", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.transfer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Seq(); ok {
		if err := transferchunk.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := transferchunk.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.data": %w`, err)}
		}
	}
	return nil
}

func (_u *TransferChunkUpdateOne) sqlSave(ctx context.Context) (_node *TransferChunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferchunk.Table, transferchunk.Columns, sqlgraph.NewFieldSpec(transferchunk.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransferChunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferchunk.FieldID)
		for _, f := range fields {
			if !transferchunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transferchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TransferID(); ok {
		_spec.SetField(transferchunk.FieldTransferID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(transferchunk.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(transferchunk.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(transferchunk.FieldData, field.TypeBytes, value)
	}
	_node = &TransferChunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
