// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/transfersession"
)

// TransferSessionCreate is the builder for creating a TransferSession entity.
type TransferSessionCreate struct {
	config
	mutation *TransferSessionMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TransferSessionCreate) SetTenantID(v string) *TransferSessionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableTenantID(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *TransferSessionCreate) SetWorkflowID(v string) *TransferSessionCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableWorkflowID(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetWorkflowID(*v)
	}
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *TransferSessionCreate) SetExecutionID(v string) *TransferSessionCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableExecutionID(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetExecutionID(*v)
	}
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *TransferSessionCreate) SetNodeID(v string) *TransferSessionCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableNodeID(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetSenderClientID sets the "sender_client_id" field.
func (_c *TransferSessionCreate) SetSenderClientID(v string) *TransferSessionCreate {
	_c.mutation.SetSenderClientID(v)
	return _c
}

// SetReceiverClientID sets the "receiver_client_id" field.
func (_c *TransferSessionCreate) SetReceiverClientID(v string) *TransferSessionCreate {
	_c.mutation.SetReceiverClientID(v)
	return _c
}

// SetNillableReceiverClientID sets the "receiver_client_id" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableReceiverClientID(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetReceiverClientID(*v)
	}
	return _c
}

// SetReceiverTags sets the "receiver_tags" field.
func (_c *TransferSessionCreate) SetReceiverTags(v []string) *TransferSessionCreate {
	_c.mutation.SetReceiverTags(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *TransferSessionCreate) SetFileName(v string) *TransferSessionCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableFileName(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetDestinationFile sets the "destination_file" field.
func (_c *TransferSessionCreate) SetDestinationFile(v string) *TransferSessionCreate {
	_c.mutation.SetDestinationFile(v)
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *TransferSessionCreate) SetPermissions(v string) *TransferSessionCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillablePermissions(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetPermissions(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *TransferSessionCreate) SetSize(v int64) *TransferSessionCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableSize(v *int64) *TransferSessionCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *TransferSessionCreate) SetSha256(v string) *TransferSessionCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableSha256(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TransferSessionCreate) SetStatus(v string) *TransferSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableStatus(v *string) *TransferSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetViaP2p sets the "via_p2p" field.
func (_c *TransferSessionCreate) SetViaP2p(v bool) *TransferSessionCreate {
	_c.mutation.SetViaP2p(v)
	return _c
}

// SetNillableViaP2p sets the "via_p2p" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableViaP2p(v *bool) *TransferSessionCreate {
	if v != nil {
		_c.SetViaP2p(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransferSessionCreate) SetCreatedAt(v time.Time) *TransferSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableCreatedAt(v *time.Time) *TransferSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TransferSessionCreate) SetUpdatedAt(v time.Time) *TransferSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TransferSessionCreate) SetNillableUpdatedAt(v *time.Time) *TransferSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransferSessionCreate) SetID(v string) *TransferSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TransferSessionMutation object of the builder.
func (_c *TransferSessionCreate) Mutation() *TransferSessionMutation {
	return _c.mutation
}

// Save creates the TransferSession in the database.
func (_c *TransferSessionCreate) Save(ctx context.Context) (*TransferSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferSessionCreate) SaveX(ctx context.Context) *TransferSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransferSessionCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := transfersession.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.WorkflowID(); !ok {
		v := transfersession.DefaultWorkflowID
		_c.mutation.SetWorkflowID(v)
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		v := transfersession.DefaultExecutionID
		_c.mutation.SetExecutionID(v)
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		v := transfersession.DefaultNodeID
		_c.mutation.SetNodeID(v)
	}
	if _, ok := _c.mutation.ReceiverClientID(); !ok {
		v := transfersession.DefaultReceiverClientID
		_c.mutation.SetReceiverClientID(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := transfersession.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		v := transfersession.DefaultPermissions
		_c.mutation.SetPermissions(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := transfersession.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		v := transfersession.DefaultSha256
		_c.mutation.SetSha256(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := transfersession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ViaP2p(); !ok {
		v := transfersession.DefaultViaP2p
		_c.mutation.SetViaP2p(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transfersession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := transfersession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferSessionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TransferSession.tenant_id"`)}
	}
	if _, ok := _c.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "TransferSession.workflow_id"`)}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "TransferSession.execution_id"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "TransferSession.node_id"`)}
	}
	if _, ok := _c.mutation.SenderClientID(); !ok {
		return &ValidationError{Name: "sender_client_id", err: errors.New(`ent: missing required field "TransferSession.sender_client_id"`)}
	}
	if v, ok := _c.mutation.SenderClientID(); ok {
		if err := transfersession.SenderClientIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_client_id", err: fmt.Errorf(`ent: validator failed for field "TransferSession.sender_client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReceiverClientID(); !ok {
		return &ValidationError{Name: "receiver_client_id", err: errors.New(`ent: missing required field "TransferSession.receiver_client_id"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "TransferSession.file_name"`)}
	}
	if _, ok := _c.mutation.DestinationFile(); !ok {
		return &ValidationError{Name: "destination_file", err: errors.New(`ent: missing required field "TransferSession.destination_file"`)}
	}
	if v, ok := _c.mutation.DestinationFile(); ok {
		if err := transfersession.DestinationFileValidator(v); err != nil {
			return &ValidationError{Name: "destination_file", err: fmt.Errorf(`ent: validator failed for field "TransferSession.destination_file": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "TransferSession.permissions"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "TransferSession.size"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "TransferSession.sha256"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TransferSession.status"`)}
	}
	if _, ok := _c.mutation.ViaP2p(); !ok {
		return &ValidationError{Name: "via_p2p", err: errors.New(`ent: missing required field "TransferSession.via_p2p"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TransferSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TransferSession.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := transfersession.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TransferSession.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TransferSessionCreate) sqlSave(ctx context.Context) (*TransferSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TransferSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferSessionCreate) createSpec() (*TransferSession, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transfersession.Table, sqlgraph.NewFieldSpec(transfersession.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(transfersession.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.WorkflowID(); ok {
		_spec.SetField(transfersession.FieldWorkflowID, field.TypeString, value)
		_node.WorkflowID = value
	}
	if value, ok := _c.mutation.ExecutionID(); ok {
		_spec.SetField(transfersession.FieldExecutionID, field.TypeString, value)
		_node.ExecutionID = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(transfersession.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.SenderClientID(); ok {
		_spec.SetField(transfersession.FieldSenderClientID, field.TypeString, value)
		_node.SenderClientID = value
	}
	if value, ok := _c.mutation.ReceiverClientID(); ok {
		_spec.SetField(transfersession.FieldReceiverClientID, field.TypeString, value)
		_node.ReceiverClientID = value
	}
	if value, ok := _c.mutation.ReceiverTags(); ok {
		_spec.SetField(transfersession.FieldReceiverTags, field.TypeJSON, value)
		_node.ReceiverTags = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(transfersession.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.DestinationFile(); ok {
		_spec.SetField(transfersession.FieldDestinationFile, field.TypeString, value)
		_node.DestinationFile = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(transfersession.FieldPermissions, field.TypeString, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(transfersession.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(transfersession.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(transfersession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ViaP2p(); ok {
		_spec.SetField(transfersession.FieldViaP2p, field.TypeBool, value)
		_node.ViaP2p = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transfersession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(transfersession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TransferSessionCreateBulk is the builder for creating many TransferSession entities in bulk.
type TransferSessionCreateBulk struct {
	config
	err      error
	builders []*TransferSessionCreate
}

// Save creates the TransferSession entities in the database.
func (_c *TransferSessionCreateBulk) Save(ctx context.Context) ([]*TransferSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferSessionCreateBulk) SaveX(ctx context.Context) []*TransferSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
