// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mcmx/nitejaguar/ent/transfersignal"
)

// TransferSignal is the model entity for the TransferSignal schema.
type TransferSignal struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TransferID holds the value of the "transfer_id" field.
	TransferID string `json:"transfer_id,omitempty"`
	// FromClientID holds the value of the "from_client_id" field.
	FromClientID string `json:"from_client_id,omitempty"`
	// offer, answer, ice or bye
	Kind string `json:"kind,omitempty"`
	// SDP or ICE JSON, max 64KiB
	Payload string `json:"payload,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransferSignal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transfersignal.FieldID, transfersignal.FieldTransferID, transfersignal.FieldFromClientID, transfersignal.FieldKind, transfersignal.FieldPayload:
			values[i] = new(sql.NullString)
		case transfersignal.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransferSignal fields.
func (_m *TransferSignal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transfersignal.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case transfersignal.FieldTransferID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_id", values[i])
			} else if value.Valid {
				_m.TransferID = value.String
			}
		case transfersignal.FieldFromClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_client_id", values[i])
			} else if value.Valid {
				_m.FromClientID = value.String
			}
		case transfersignal.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case transfersignal.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case transfersignal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TransferSignal.
// This includes values selected through modifiers, order, etc.
func (_m *TransferSignal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TransferSignal.
// Note that you need to call TransferSignal.Unwrap() before calling this method if this TransferSignal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TransferSignal) Update() *TransferSignalUpdateOne {
	return NewTransferSignalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TransferSignal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TransferSignal) Unwrap() *TransferSignal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransferSignal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TransferSignal) String() string {
	var builder strings.Builder
	builder.WriteString("TransferSignal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("transfer_id=")
	builder.WriteString(_m.TransferID)
	builder.WriteString(", ")
	builder.WriteString("from_client_id=")
	builder.WriteString(_m.FromClientID)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TransferSignals is a parsable slice of TransferSignal.
type TransferSignals []*TransferSignal
