// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/predicate"
	"github.com/mcmx/nitejaguar/ent/transferchunk"
)

// TransferChunkDelete is the builder for deleting a TransferChunk entity.
type TransferChunkDelete struct {
	config
	hooks    []Hook
	mutation *TransferChunkMutation
}

// Where appends a list predicates to the TransferChunkDelete builder.
func (_d *TransferChunkDelete) Where(ps ...predicate.TransferChunk) *TransferChunkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TransferChunkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TransferChunkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TransferChunkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transferchunk.Table, sqlgraph.NewFieldSpec(transferchunk.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TransferChunkDeleteOne is the builder for deleting a single TransferChunk entity.
type TransferChunkDeleteOne struct {
	_d *TransferChunkDelete
}

// Where appends a list predicates to the TransferChunkDelete builder.
func (_d *TransferChunkDeleteOne) Where(ps ...predicate.TransferChunk) *TransferChunkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TransferChunkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transferchunk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TransferChunkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
