// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/transferchunk"
)

// TransferChunkCreate is the builder for creating a TransferChunk entity.
type TransferChunkCreate struct {
	config
	mutation *TransferChunkMutation
	hooks    []Hook
}

// SetTransferID sets the "transfer_id" field.
func (_c *TransferChunkCreate) SetTransferID(v string) *TransferChunkCreate {
	_c.mutation.SetTransferID(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *TransferChunkCreate) SetSeq(v int) *TransferChunkCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetData sets the "data" field.
func (_c *TransferChunkCreate) SetData(v []byte) *TransferChunkCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransferChunkCreate) SetCreatedAt(v time.Time) *TransferChunkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransferChunkCreate) SetNillableCreatedAt(v *time.Time) *TransferChunkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransferChunkCreate) SetID(v string) *TransferChunkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TransferChunkMutation object of the builder.
func (_c *TransferChunkCreate) Mutation() *TransferChunkMutation {
	return _c.mutation
}

// Save creates the TransferChunk in the database.
func (_c *TransferChunkCreate) Save(ctx context.Context) (*TransferChunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferChunkCreate) SaveX(ctx context.Context) *TransferChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransferChunkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transferchunk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferChunkCreate) check() error {
	if _, ok := _c.mutation.TransferID(); !ok {
		return &ValidationError{Name: "transfer_id", err: errors.New(`ent: missing required field "TransferChunk.transfer_id"`)}
	}
	if v, ok := _c.mutation.TransferID(); ok {
		if err := transferchunk.TransferIDValidator(v); err != nil {
			return &ValidationError{Name: "transfer_id", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.transfer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "TransferChunk.seq"`)}
	}
	if v, ok := _c.mutation.Seq(); ok {
		if err := transferchunk.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "TransferChunk.data"`)}
	}
	if v, ok := _c.mutation.Data(); ok {
		if err := transferchunk.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.data": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TransferChunk.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := transferchunk.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TransferChunk.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TransferChunkCreate) sqlSave(ctx context.Context) (*TransferChunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TransferChunk.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferChunkCreate) createSpec() (*TransferChunk, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferChunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transferchunk.Table, sqlgraph.NewFieldSpec(transferchunk.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TransferID(); ok {
		_spec.SetField(transferchunk.FieldTransferID, field.TypeString, value)
		_node.TransferID = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(transferchunk.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(transferchunk.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transferchunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TransferChunkCreateBulk is the builder for creating many TransferChunk entities in bulk.
type TransferChunkCreateBulk struct {
	config
	err      error
	builders []*TransferChunkCreate
}

// Save creates the TransferChunk entities in the database.
func (_c *TransferChunkCreateBulk) Save(ctx context.Context) ([]*TransferChunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferChunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferChunkCreateBulk) SaveX(ctx context.Context) []*TransferChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
