// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/transfersignal"
)

// TransferSignalCreate is the builder for creating a TransferSignal entity.
type TransferSignalCreate struct {
	config
	mutation *TransferSignalMutation
	hooks    []Hook
}

// SetTransferID sets the "transfer_id" field.
func (_c *TransferSignalCreate) SetTransferID(v string) *TransferSignalCreate {
	_c.mutation.SetTransferID(v)
	return _c
}

// SetFromClientID sets the "from_client_id" field.
func (_c *TransferSignalCreate) SetFromClientID(v string) *TransferSignalCreate {
	_c.mutation.SetFromClientID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TransferSignalCreate) SetKind(v string) *TransferSignalCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *TransferSignalCreate) SetPayload(v string) *TransferSignalCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *TransferSignalCreate) SetNillablePayload(v *string) *TransferSignalCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransferSignalCreate) SetCreatedAt(v time.Time) *TransferSignalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransferSignalCreate) SetNillableCreatedAt(v *time.Time) *TransferSignalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransferSignalCreate) SetID(v string) *TransferSignalCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TransferSignalMutation object of the builder.
func (_c *TransferSignalCreate) Mutation() *TransferSignalMutation {
	return _c.mutation
}

// Save creates the TransferSignal in the database.
func (_c *TransferSignalCreate) Save(ctx context.Context) (*TransferSignal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferSignalCreate) SaveX(ctx context.Context) *TransferSignal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferSignalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferSignalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransferSignalCreate) defaults() {
	if _, ok := _c.mutation.Payload(); !ok {
		v := transfersignal.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transfersignal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferSignalCreate) check() error {
	if _, ok := _c.mutation.TransferID(); !ok {
		return &ValidationError{Name: "transfer_id", err: errors.New(`ent: missing required field "TransferSignal.transfer_id"`)}
	}
	if v, ok := _c.mutation.TransferID(); ok {
		if err := transfersignal.TransferIDValidator(v); err != nil {
			return &ValidationError{Name: "transfer_id", err: fmt.Errorf(`ent: validator failed for field "TransferSignal.transfer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromClientID(); !ok {
		return &ValidationError{Name: "from_client_id", err: errors.New(`ent: missing required field "TransferSignal.from_client_id"`)}
	}
	if v, ok := _c.mutation.FromClientID(); ok {
		if err := transfersignal.FromClientIDValidator(v); err != nil {
			return &ValidationError{Name: "from_client_id", err: fmt.Errorf(`ent: validator failed for field "TransferSignal.from_client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "TransferSignal.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := transfersignal.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "TransferSignal.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "TransferSignal.payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TransferSignal.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := transfersignal.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TransferSignal.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TransferSignalCreate) sqlSave(ctx context.Context) (*TransferSignal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TransferSignal.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferSignalCreate) createSpec() (*TransferSignal, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferSignal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transfersignal.Table, sqlgraph.NewFieldSpec(transfersignal.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TransferID(); ok {
		_spec.SetField(transfersignal.FieldTransferID, field.TypeString, value)
		_node.TransferID = value
	}
	if value, ok := _c.mutation.FromClientID(); ok {
		_spec.SetField(transfersignal.FieldFromClientID, field.TypeString, value)
		_node.FromClientID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(transfersignal.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(transfersignal.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transfersignal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TransferSignalCreateBulk is the builder for creating many TransferSignal entities in bulk.
type TransferSignalCreateBulk struct {
	config
	err      error
	builders []*TransferSignalCreate
}

// Save creates the TransferSignal entities in the database.
func (_c *TransferSignalCreateBulk) Save(ctx context.Context) ([]*TransferSignal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferSignal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferSignalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferSignalCreateBulk) SaveX(ctx context.Context) []*TransferSignal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferSignalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferSignalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
