// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/predicate"
	"github.com/mcmx/nitejaguar/ent/workflow"
)

// WorkflowUpdate is the builder for updating Workflow entities.
type WorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowMutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (_u *WorkflowUpdate) Where(ps ...predicate.Workflow) *WorkflowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkflowUpdate) SetEnabled(v bool) *WorkflowUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableEnabled(v *bool) *WorkflowUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *WorkflowUpdate) SetTenantID(v string) *WorkflowUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableTenantID(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetJSONDefinition sets the "json_definition" field.
func (_u *WorkflowUpdate) SetJSONDefinition(v string) *WorkflowUpdate {
	_u.mutation.SetJSONDefinition(v)
	return _u
}

// SetNillableJSONDefinition sets the "json_definition" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableJSONDefinition(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetJSONDefinition(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowUpdate) SetUpdatedAt(v time.Time) *WorkflowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkflowMutation object of the builder.
func (_u *WorkflowUpdate) Mutation() *WorkflowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowUpdate) check() error {
	if v, ok := _u.mutation.JSONDefinition(); ok {
		if err := workflow.JSONDefinitionValidator(v); err != nil {
			return &ValidationError{Name: "json_definition", err: fmt.Errorf(`ent: validator failed for field "Workflow.json_definition": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workflow.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(workflow.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.JSONDefinition(); ok {
		_spec.SetField(workflow.FieldJSONDefinition, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowUpdateOne is the builder for updating a single Workflow entity.
type WorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowMutation
}

// SetEnabled sets the "enabled" field.
func (_u *WorkflowUpdateOne) SetEnabled(v bool) *WorkflowUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableEnabled(v *bool) *WorkflowUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *WorkflowUpdateOne) SetTenantID(v string) *WorkflowUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableTenantID(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetJSONDefinition sets the "json_definition" field.
func (_u *WorkflowUpdateOne) SetJSONDefinition(v string) *WorkflowUpdateOne {
	_u.mutation.SetJSONDefinition(v)
	return _u
}

// SetNillableJSONDefinition sets the "json_definition" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableJSONDefinition(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetJSONDefinition(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowUpdateOne) SetUpdatedAt(v time.Time) *WorkflowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkflowMutation object of the builder.
func (_u *WorkflowUpdateOne) Mutation() *WorkflowMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (_u *WorkflowUpdateOne) Where(ps ...predicate.Workflow) *WorkflowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowUpdateOne) Select(field string, fields ...string) *WorkflowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workflow entity.
func (_u *WorkflowUpdateOne) Save(ctx context.Context) (*Workflow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowUpdateOne) SaveX(ctx context.Context) *Workflow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowUpdateOne) check() error {
	if v, ok := _u.mutation.JSONDefinition(); ok {
		if err := workflow.JSONDefinitionValidator(v); err != nil {
			return &ValidationError{Name: "json_definition", err: fmt.Errorf(`ent: validator failed for field "Workflow.json_definition": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowUpdateOne) sqlSave(ctx context.Context) (_node *Workflow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for _, f := range fields {
			if !workflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workflow.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(workflow.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.JSONDefinition(); ok {
		_spec.SetField(workflow.FieldJSONDefinition, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Workflow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
