// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mcmx/nitejaguar/ent/workflowresult"
)

// WorkflowResult is the model entity for the WorkflowResult schema.
type WorkflowResult struct {
	config `json:"-"`
	// ID of the ent.
	// result_id (result_ typeid)
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID string `json:"workflow_id,omitempty"`
	// ExecutionID holds the value of the "execution_id" field.
	ExecutionID string `json:"execution_id,omitempty"`
	// node id that produced the result
	ActionID string `json:"action_id,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType string `json:"action_type,omitempty"`
	// ActionName holds the value of the "action_name" field.
	ActionName string `json:"action_name,omitempty"`
	// ExecutorID holds the value of the "executor_id" field.
	ExecutorID string `json:"executor_id,omitempty"`
	// ResultData payload, JSON-encoded
	PayloadJSON string `json:"payload_json,omitempty"`
	// per-entry condition outcomes (entry ID -> matched), JSON-encoded
	ConditionResultsJSON string `json:"condition_results_json,omitempty"`
	// downstream node IDs whose entry condition matched
	Nexts []string `json:"nexts,omitempty"`
	// first condition evaluation error, if any
	ConditionError string `json:"condition_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowresult.FieldNexts:
			values[i] = new([]byte)
		case workflowresult.FieldID, workflowresult.FieldTenantID, workflowresult.FieldWorkflowID, workflowresult.FieldExecutionID, workflowresult.FieldActionID, workflowresult.FieldActionType, workflowresult.FieldActionName, workflowresult.FieldExecutorID, workflowresult.FieldPayloadJSON, workflowresult.FieldConditionResultsJSON, workflowresult.FieldConditionError:
			values[i] = new(sql.NullString)
		case workflowresult.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowResult fields.
func (_m *WorkflowResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowresult.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case workflowresult.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case workflowresult.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				_m.WorkflowID = value.String
			}
		case workflowresult.FieldExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = value.String
			}
		case workflowresult.FieldActionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_id", values[i])
			} else if value.Valid {
				_m.ActionID = value.String
			}
		case workflowresult.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = value.String
			}
		case workflowresult.FieldActionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_name", values[i])
			} else if value.Valid {
				_m.ActionName = value.String
			}
		case workflowresult.FieldExecutorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field executor_id", values[i])
			} else if value.Valid {
				_m.ExecutorID = value.String
			}
		case workflowresult.FieldPayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_json", values[i])
			} else if value.Valid {
				_m.PayloadJSON = value.String
			}
		case workflowresult.FieldConditionResultsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition_results_json", values[i])
			} else if value.Valid {
				_m.ConditionResultsJSON = value.String
			}
		case workflowresult.FieldNexts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nexts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Nexts); err != nil {
					return fmt.Errorf("unmarshal field nexts: %w", err)
				}
			}
		case workflowresult.FieldConditionError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition_error", values[i])
			} else if value.Valid {
				_m.ConditionError = value.String
			}
		case workflowresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowResult.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowResult.
// Note that you need to call WorkflowResult.Unwrap() before calling this method if this WorkflowResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowResult) Update() *WorkflowResultUpdateOne {
	return NewWorkflowResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowResult) Unwrap() *WorkflowResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowResult) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(_m.WorkflowID)
	builder.WriteString(", ")
	builder.WriteString("execution_id=")
	builder.WriteString(_m.ExecutionID)
	builder.WriteString(", ")
	builder.WriteString("action_id=")
	builder.WriteString(_m.ActionID)
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(_m.ActionType)
	builder.WriteString(", ")
	builder.WriteString("action_name=")
	builder.WriteString(_m.ActionName)
	builder.WriteString(", ")
	builder.WriteString("executor_id=")
	builder.WriteString(_m.ExecutorID)
	builder.WriteString(", ")
	builder.WriteString("payload_json=")
	builder.WriteString(_m.PayloadJSON)
	builder.WriteString(", ")
	builder.WriteString("condition_results_json=")
	builder.WriteString(_m.ConditionResultsJSON)
	builder.WriteString(", ")
	builder.WriteString("nexts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Nexts))
	builder.WriteString(", ")
	builder.WriteString("condition_error=")
	builder.WriteString(_m.ConditionError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowResults is a parsable slice of WorkflowResult.
type WorkflowResults []*WorkflowResult
