// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/predicate"
	"github.com/mcmx/nitejaguar/ent/workflowresult"
)

// WorkflowResultUpdate is the builder for updating WorkflowResult entities.
type WorkflowResultUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowResultMutation
}

// Where appends a list predicates to the WorkflowResultUpdate builder.
func (_u *WorkflowResultUpdate) Where(ps ...predicate.WorkflowResult) *WorkflowResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *WorkflowResultUpdate) SetTenantID(v string) *WorkflowResultUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableTenantID(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *WorkflowResultUpdate) SetWorkflowID(v string) *WorkflowResultUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableWorkflowID(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *WorkflowResultUpdate) SetExecutionID(v string) *WorkflowResultUpdate {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableExecutionID(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *WorkflowResultUpdate) SetActionID(v string) *WorkflowResultUpdate {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableActionID(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *WorkflowResultUpdate) SetActionType(v string) *WorkflowResultUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableActionType(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionName sets the "action_name" field.
func (_u *WorkflowResultUpdate) SetActionName(v string) *WorkflowResultUpdate {
	_u.mutation.SetActionName(v)
	return _u
}

// SetNillableActionName sets the "action_name" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableActionName(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetActionName(*v)
	}
	return _u
}

// SetExecutorID sets the "executor_id" field.
func (_u *WorkflowResultUpdate) SetExecutorID(v string) *WorkflowResultUpdate {
	_u.mutation.SetExecutorID(v)
	return _u
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableExecutorID(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetExecutorID(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *WorkflowResultUpdate) SetPayloadJSON(v string) *WorkflowResultUpdate {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillablePayloadJSON(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetConditionResultsJSON sets the "condition_results_json" field.
func (_u *WorkflowResultUpdate) SetConditionResultsJSON(v string) *WorkflowResultUpdate {
	_u.mutation.SetConditionResultsJSON(v)
	return _u
}

// SetNillableConditionResultsJSON sets the "condition_results_json" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableConditionResultsJSON(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetConditionResultsJSON(*v)
	}
	return _u
}

// SetNexts sets the "nexts" field.
func (_u *WorkflowResultUpdate) SetNexts(v []string) *WorkflowResultUpdate {
	_u.mutation.SetNexts(v)
	return _u
}

// AppendNexts appends value to the "nexts" field.
func (_u *WorkflowResultUpdate) AppendNexts(v []string) *WorkflowResultUpdate {
	_u.mutation.AppendNexts(v)
	return _u
}

// ClearNexts clears the value of the "nexts" field.
func (_u *WorkflowResultUpdate) ClearNexts() *WorkflowResultUpdate {
	_u.mutation.ClearNexts()
	return _u
}

// SetConditionError sets the "condition_error" field.
func (_u *WorkflowResultUpdate) SetConditionError(v string) *WorkflowResultUpdate {
	_u.mutation.SetConditionError(v)
	return _u
}

// SetNillableConditionError sets the "condition_error" field if the given value is not nil.
func (_u *WorkflowResultUpdate) SetNillableConditionError(v *string) *WorkflowResultUpdate {
	if v != nil {
		_u.SetConditionError(*v)
	}
	return _u
}

// Mutation returns the WorkflowResultMutation object of the builder.
func (_u *WorkflowResultUpdate) Mutation() *WorkflowResultMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowResultUpdate) check() error {
	if v, ok := _u.mutation.WorkflowID(); ok {
		if err := workflowresult.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.workflow_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionID(); ok {
		if err := workflowresult.ActionIDValidator(v); err != nil {
			return &ValidationError{Name: "action_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.action_id": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowresult.Table, workflowresult.Columns, sqlgraph.NewFieldSpec(workflowresult.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(workflowresult.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(workflowresult.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(workflowresult.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(workflowresult.FieldActionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(workflowresult.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionName(); ok {
		_spec.SetField(workflowresult.FieldActionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutorID(); ok {
		_spec.SetField(workflowresult.FieldExecutorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(workflowresult.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionResultsJSON(); ok {
		_spec.SetField(workflowresult.FieldConditionResultsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nexts(); ok {
		_spec.SetField(workflowresult.FieldNexts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNexts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflowresult.FieldNexts, value)
		})
	}
	if _u.mutation.NextsCleared() {
		_spec.ClearField(workflowresult.FieldNexts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConditionError(); ok {
		_spec.SetField(workflowresult.FieldConditionError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowResultUpdateOne is the builder for updating a single WorkflowResult entity.
type WorkflowResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowResultMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *WorkflowResultUpdateOne) SetTenantID(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableTenantID(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *WorkflowResultUpdateOne) SetWorkflowID(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableWorkflowID(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *WorkflowResultUpdateOne) SetExecutionID(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableExecutionID(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *WorkflowResultUpdateOne) SetActionID(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableActionID(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *WorkflowResultUpdateOne) SetActionType(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableActionType(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionName sets the "action_name" field.
func (_u *WorkflowResultUpdateOne) SetActionName(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetActionName(v)
	return _u
}

// SetNillableActionName sets the "action_name" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableActionName(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetActionName(*v)
	}
	return _u
}

// SetExecutorID sets the "executor_id" field.
func (_u *WorkflowResultUpdateOne) SetExecutorID(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetExecutorID(v)
	return _u
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableExecutorID(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetExecutorID(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *WorkflowResultUpdateOne) SetPayloadJSON(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillablePayloadJSON(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetConditionResultsJSON sets the "condition_results_json" field.
func (_u *WorkflowResultUpdateOne) SetConditionResultsJSON(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetConditionResultsJSON(v)
	return _u
}

// SetNillableConditionResultsJSON sets the "condition_results_json" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableConditionResultsJSON(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetConditionResultsJSON(*v)
	}
	return _u
}

// SetNexts sets the "nexts" field.
func (_u *WorkflowResultUpdateOne) SetNexts(v []string) *WorkflowResultUpdateOne {
	_u.mutation.SetNexts(v)
	return _u
}

// AppendNexts appends value to the "nexts" field.
func (_u *WorkflowResultUpdateOne) AppendNexts(v []string) *WorkflowResultUpdateOne {
	_u.mutation.AppendNexts(v)
	return _u
}

// ClearNexts clears the value of the "nexts" field.
func (_u *WorkflowResultUpdateOne) ClearNexts() *WorkflowResultUpdateOne {
	_u.mutation.ClearNexts()
	return _u
}

// SetConditionError sets the "condition_error" field.
func (_u *WorkflowResultUpdateOne) SetConditionError(v string) *WorkflowResultUpdateOne {
	_u.mutation.SetConditionError(v)
	return _u
}

// SetNillableConditionError sets the "condition_error" field if the given value is not nil.
func (_u *WorkflowResultUpdateOne) SetNillableConditionError(v *string) *WorkflowResultUpdateOne {
	if v != nil {
		_u.SetConditionError(*v)
	}
	return _u
}

// Mutation returns the WorkflowResultMutation object of the builder.
func (_u *WorkflowResultUpdateOne) Mutation() *WorkflowResultMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowResultUpdate builder.
func (_u *WorkflowResultUpdateOne) Where(ps ...predicate.WorkflowResult) *WorkflowResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowResultUpdateOne) Select(field string, fields ...string) *WorkflowResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowResult entity.
func (_u *WorkflowResultUpdateOne) Save(ctx context.Context) (*WorkflowResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowResultUpdateOne) SaveX(ctx context.Context) *WorkflowResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowResultUpdateOne) check() error {
	if v, ok := _u.mutation.WorkflowID(); ok {
		if err := workflowresult.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.workflow_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionID(); ok {
		if err := workflowresult.ActionIDValidator(v); err != nil {
			return &ValidationError{Name: "action_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.action_id": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowResultUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowresult.Table, workflowresult.Columns, sqlgraph.NewFieldSpec(workflowresult.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowresult.FieldID)
		for _, f := range fields {
			if !workflowresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(workflowresult.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(workflowresult.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(workflowresult.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(workflowresult.FieldActionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(workflowresult.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionName(); ok {
		_spec.SetField(workflowresult.FieldActionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutorID(); ok {
		_spec.SetField(workflowresult.FieldExecutorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(workflowresult.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionResultsJSON(); ok {
		_spec.SetField(workflowresult.FieldConditionResultsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nexts(); ok {
		_spec.SetField(workflowresult.FieldNexts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNexts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflowresult.FieldNexts, value)
		})
	}
	if _u.mutation.NextsCleared() {
		_spec.ClearField(workflowresult.FieldNexts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConditionError(); ok {
		_spec.SetField(workflowresult.FieldConditionError, field.TypeString, value)
	}
	_node = &WorkflowResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
