// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mcmx/nitejaguar/ent/workflowresult"
)

// WorkflowResultCreate is the builder for creating a WorkflowResult entity.
type WorkflowResultCreate struct {
	config
	mutation *WorkflowResultMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *WorkflowResultCreate) SetTenantID(v string) *WorkflowResultCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableTenantID(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *WorkflowResultCreate) SetWorkflowID(v string) *WorkflowResultCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *WorkflowResultCreate) SetExecutionID(v string) *WorkflowResultCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableExecutionID(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetExecutionID(*v)
	}
	return _c
}

// SetActionID sets the "action_id" field.
func (_c *WorkflowResultCreate) SetActionID(v string) *WorkflowResultCreate {
	_c.mutation.SetActionID(v)
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *WorkflowResultCreate) SetActionType(v string) *WorkflowResultCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableActionType(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetActionType(*v)
	}
	return _c
}

// SetActionName sets the "action_name" field.
func (_c *WorkflowResultCreate) SetActionName(v string) *WorkflowResultCreate {
	_c.mutation.SetActionName(v)
	return _c
}

// SetNillableActionName sets the "action_name" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableActionName(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetActionName(*v)
	}
	return _c
}

// SetExecutorID sets the "executor_id" field.
func (_c *WorkflowResultCreate) SetExecutorID(v string) *WorkflowResultCreate {
	_c.mutation.SetExecutorID(v)
	return _c
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableExecutorID(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetExecutorID(*v)
	}
	return _c
}

// SetPayloadJSON sets the "payload_json" field.
func (_c *WorkflowResultCreate) SetPayloadJSON(v string) *WorkflowResultCreate {
	_c.mutation.SetPayloadJSON(v)
	return _c
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillablePayloadJSON(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetPayloadJSON(*v)
	}
	return _c
}

// SetConditionResultsJSON sets the "condition_results_json" field.
func (_c *WorkflowResultCreate) SetConditionResultsJSON(v string) *WorkflowResultCreate {
	_c.mutation.SetConditionResultsJSON(v)
	return _c
}

// SetNillableConditionResultsJSON sets the "condition_results_json" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableConditionResultsJSON(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetConditionResultsJSON(*v)
	}
	return _c
}

// SetNexts sets the "nexts" field.
func (_c *WorkflowResultCreate) SetNexts(v []string) *WorkflowResultCreate {
	_c.mutation.SetNexts(v)
	return _c
}

// SetConditionError sets the "condition_error" field.
func (_c *WorkflowResultCreate) SetConditionError(v string) *WorkflowResultCreate {
	_c.mutation.SetConditionError(v)
	return _c
}

// SetNillableConditionError sets the "condition_error" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableConditionError(v *string) *WorkflowResultCreate {
	if v != nil {
		_c.SetConditionError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkflowResultCreate) SetCreatedAt(v time.Time) *WorkflowResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkflowResultCreate) SetNillableCreatedAt(v *time.Time) *WorkflowResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkflowResultCreate) SetID(v string) *WorkflowResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WorkflowResultMutation object of the builder.
func (_c *WorkflowResultCreate) Mutation() *WorkflowResultMutation {
	return _c.mutation
}

// Save creates the WorkflowResult in the database.
func (_c *WorkflowResultCreate) Save(ctx context.Context) (*WorkflowResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkflowResultCreate) SaveX(ctx context.Context) *WorkflowResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkflowResultCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := workflowresult.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		v := workflowresult.DefaultExecutionID
		_c.mutation.SetExecutionID(v)
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		v := workflowresult.DefaultActionType
		_c.mutation.SetActionType(v)
	}
	if _, ok := _c.mutation.ActionName(); !ok {
		v := workflowresult.DefaultActionName
		_c.mutation.SetActionName(v)
	}
	if _, ok := _c.mutation.ExecutorID(); !ok {
		v := workflowresult.DefaultExecutorID
		_c.mutation.SetExecutorID(v)
	}
	if _, ok := _c.mutation.PayloadJSON(); !ok {
		v := workflowresult.DefaultPayloadJSON
		_c.mutation.SetPayloadJSON(v)
	}
	if _, ok := _c.mutation.ConditionResultsJSON(); !ok {
		v := workflowresult.DefaultConditionResultsJSON
		_c.mutation.SetConditionResultsJSON(v)
	}
	if _, ok := _c.mutation.ConditionError(); !ok {
		v := workflowresult.DefaultConditionError
		_c.mutation.SetConditionError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workflowresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkflowResultCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "WorkflowResult.tenant_id"`)}
	}
	if _, ok := _c.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "WorkflowResult.workflow_id"`)}
	}
	if v, ok := _c.mutation.WorkflowID(); ok {
		if err := workflowresult.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.workflow_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "WorkflowResult.execution_id"`)}
	}
	if _, ok := _c.mutation.ActionID(); !ok {
		return &ValidationError{Name: "action_id", err: errors.New(`ent: missing required field "WorkflowResult.action_id"`)}
	}
	if v, ok := _c.mutation.ActionID(); ok {
		if err := workflowresult.ActionIDValidator(v); err != nil {
			return &ValidationError{Name: "action_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.action_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "WorkflowResult.action_type"`)}
	}
	if _, ok := _c.mutation.ActionName(); !ok {
		return &ValidationError{Name: "action_name", err: errors.New(`ent: missing required field "WorkflowResult.action_name"`)}
	}
	if _, ok := _c.mutation.ExecutorID(); !ok {
		return &ValidationError{Name: "executor_id", err: errors.New(`ent: missing required field "WorkflowResult.executor_id"`)}
	}
	if _, ok := _c.mutation.PayloadJSON(); !ok {
		return &ValidationError{Name: "payload_json", err: errors.New(`ent: missing required field "WorkflowResult.payload_json"`)}
	}
	if _, ok := _c.mutation.ConditionResultsJSON(); !ok {
		return &ValidationError{Name: "condition_results_json", err: errors.New(`ent: missing required field "WorkflowResult.condition_results_json"`)}
	}
	if _, ok := _c.mutation.ConditionError(); !ok {
		return &ValidationError{Name: "condition_error", err: errors.New(`ent: missing required field "WorkflowResult.condition_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkflowResult.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := workflowresult.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "WorkflowResult.id": %w`, err)}
		}
	}
	return nil
}

func (_c *WorkflowResultCreate) sqlSave(ctx context.Context) (*WorkflowResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WorkflowResult.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkflowResultCreate) createSpec() (*WorkflowResult, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workflowresult.Table, sqlgraph.NewFieldSpec(workflowresult.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(workflowresult.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.WorkflowID(); ok {
		_spec.SetField(workflowresult.FieldWorkflowID, field.TypeString, value)
		_node.WorkflowID = value
	}
	if value, ok := _c.mutation.ExecutionID(); ok {
		_spec.SetField(workflowresult.FieldExecutionID, field.TypeString, value)
		_node.ExecutionID = value
	}
	if value, ok := _c.mutation.ActionID(); ok {
		_spec.SetField(workflowresult.FieldActionID, field.TypeString, value)
		_node.ActionID = value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(workflowresult.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.ActionName(); ok {
		_spec.SetField(workflowresult.FieldActionName, field.TypeString, value)
		_node.ActionName = value
	}
	if value, ok := _c.mutation.ExecutorID(); ok {
		_spec.SetField(workflowresult.FieldExecutorID, field.TypeString, value)
		_node.ExecutorID = value
	}
	if value, ok := _c.mutation.PayloadJSON(); ok {
		_spec.SetField(workflowresult.FieldPayloadJSON, field.TypeString, value)
		_node.PayloadJSON = value
	}
	if value, ok := _c.mutation.ConditionResultsJSON(); ok {
		_spec.SetField(workflowresult.FieldConditionResultsJSON, field.TypeString, value)
		_node.ConditionResultsJSON = value
	}
	if value, ok := _c.mutation.Nexts(); ok {
		_spec.SetField(workflowresult.FieldNexts, field.TypeJSON, value)
		_node.Nexts = value
	}
	if value, ok := _c.mutation.ConditionError(); ok {
		_spec.SetField(workflowresult.FieldConditionError, field.TypeString, value)
		_node.ConditionError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workflowresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// WorkflowResultCreateBulk is the builder for creating many WorkflowResult entities in bulk.
type WorkflowResultCreateBulk struct {
	config
	err      error
	builders []*WorkflowResultCreate
}

// Save creates the WorkflowResult entities in the database.
func (_c *WorkflowResultCreateBulk) Save(ctx context.Context) ([]*WorkflowResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkflowResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkflowResultCreateBulk) SaveX(ctx context.Context) []*WorkflowResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
