// Code generated by ent, DO NOT EDIT.

package workflowresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mcmx/nitejaguar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldTenantID, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldWorkflowID, v))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldExecutionID, v))
}

// ActionID applies equality check predicate on the "action_id" field. It's identical to ActionIDEQ.
func ActionID(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionID, v))
}

// ActionType applies equality check predicate on the "action_type" field. It's identical to ActionTypeEQ.
func ActionType(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionType, v))
}

// ActionName applies equality check predicate on the "action_name" field. It's identical to ActionNameEQ.
func ActionName(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionName, v))
}

// ExecutorID applies equality check predicate on the "executor_id" field. It's identical to ExecutorIDEQ.
func ExecutorID(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldExecutorID, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldPayloadJSON, v))
}

// ConditionResultsJSON applies equality check predicate on the "condition_results_json" field. It's identical to ConditionResultsJSONEQ.
func ConditionResultsJSON(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldConditionResultsJSON, v))
}

// ConditionError applies equality check predicate on the "condition_error" field. It's identical to ConditionErrorEQ.
func ConditionError(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldConditionError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldTenantID, v))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDContains applies the Contains predicate on the "workflow_id" field.
func WorkflowIDContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldWorkflowID, v))
}

// WorkflowIDHasPrefix applies the HasPrefix predicate on the "workflow_id" field.
func WorkflowIDHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldWorkflowID, v))
}

// WorkflowIDHasSuffix applies the HasSuffix predicate on the "workflow_id" field.
func WorkflowIDHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldWorkflowID, v))
}

// WorkflowIDEqualFold applies the EqualFold predicate on the "workflow_id" field.
func WorkflowIDEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldWorkflowID, v))
}

// WorkflowIDContainsFold applies the ContainsFold predicate on the "workflow_id" field.
func WorkflowIDContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldWorkflowID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldExecutionID, v))
}

// ActionIDEQ applies the EQ predicate on the "action_id" field.
func ActionIDEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionID, v))
}

// ActionIDNEQ applies the NEQ predicate on the "action_id" field.
func ActionIDNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldActionID, v))
}

// ActionIDIn applies the In predicate on the "action_id" field.
func ActionIDIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldActionID, vs...))
}

// ActionIDNotIn applies the NotIn predicate on the "action_id" field.
func ActionIDNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldActionID, vs...))
}

// ActionIDGT applies the GT predicate on the "action_id" field.
func ActionIDGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldActionID, v))
}

// ActionIDGTE applies the GTE predicate on the "action_id" field.
func ActionIDGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldActionID, v))
}

// ActionIDLT applies the LT predicate on the "action_id" field.
func ActionIDLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldActionID, v))
}

// ActionIDLTE applies the LTE predicate on the "action_id" field.
func ActionIDLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldActionID, v))
}

// ActionIDContains applies the Contains predicate on the "action_id" field.
func ActionIDContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldActionID, v))
}

// ActionIDHasPrefix applies the HasPrefix predicate on the "action_id" field.
func ActionIDHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldActionID, v))
}

// ActionIDHasSuffix applies the HasSuffix predicate on the "action_id" field.
func ActionIDHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldActionID, v))
}

// ActionIDEqualFold applies the EqualFold predicate on the "action_id" field.
func ActionIDEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldActionID, v))
}

// ActionIDContainsFold applies the ContainsFold predicate on the "action_id" field.
func ActionIDContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldActionID, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldActionType, vs...))
}

// ActionTypeGT applies the GT predicate on the "action_type" field.
func ActionTypeGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldActionType, v))
}

// ActionTypeGTE applies the GTE predicate on the "action_type" field.
func ActionTypeGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldActionType, v))
}

// ActionTypeLT applies the LT predicate on the "action_type" field.
func ActionTypeLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldActionType, v))
}

// ActionTypeLTE applies the LTE predicate on the "action_type" field.
func ActionTypeLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldActionType, v))
}

// ActionTypeContains applies the Contains predicate on the "action_type" field.
func ActionTypeContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldActionType, v))
}

// ActionTypeHasPrefix applies the HasPrefix predicate on the "action_type" field.
func ActionTypeHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldActionType, v))
}

// ActionTypeHasSuffix applies the HasSuffix predicate on the "action_type" field.
func ActionTypeHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldActionType, v))
}

// ActionTypeEqualFold applies the EqualFold predicate on the "action_type" field.
func ActionTypeEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldActionType, v))
}

// ActionTypeContainsFold applies the ContainsFold predicate on the "action_type" field.
func ActionTypeContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldActionType, v))
}

// ActionNameEQ applies the EQ predicate on the "action_name" field.
func ActionNameEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldActionName, v))
}

// ActionNameNEQ applies the NEQ predicate on the "action_name" field.
func ActionNameNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldActionName, v))
}

// ActionNameIn applies the In predicate on the "action_name" field.
func ActionNameIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldActionName, vs...))
}

// ActionNameNotIn applies the NotIn predicate on the "action_name" field.
func ActionNameNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldActionName, vs...))
}

// ActionNameGT applies the GT predicate on the "action_name" field.
func ActionNameGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldActionName, v))
}

// ActionNameGTE applies the GTE predicate on the "action_name" field.
func ActionNameGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldActionName, v))
}

// ActionNameLT applies the LT predicate on the "action_name" field.
func ActionNameLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldActionName, v))
}

// ActionNameLTE applies the LTE predicate on the "action_name" field.
func ActionNameLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldActionName, v))
}

// ActionNameContains applies the Contains predicate on the "action_name" field.
func ActionNameContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldActionName, v))
}

// ActionNameHasPrefix applies the HasPrefix predicate on the "action_name" field.
func ActionNameHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldActionName, v))
}

// ActionNameHasSuffix applies the HasSuffix predicate on the "action_name" field.
func ActionNameHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldActionName, v))
}

// ActionNameEqualFold applies the EqualFold predicate on the "action_name" field.
func ActionNameEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldActionName, v))
}

// ActionNameContainsFold applies the ContainsFold predicate on the "action_name" field.
func ActionNameContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldActionName, v))
}

// ExecutorIDEQ applies the EQ predicate on the "executor_id" field.
func ExecutorIDEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldExecutorID, v))
}

// ExecutorIDNEQ applies the NEQ predicate on the "executor_id" field.
func ExecutorIDNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldExecutorID, v))
}

// ExecutorIDIn applies the In predicate on the "executor_id" field.
func ExecutorIDIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldExecutorID, vs...))
}

// ExecutorIDNotIn applies the NotIn predicate on the "executor_id" field.
func ExecutorIDNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldExecutorID, vs...))
}

// ExecutorIDGT applies the GT predicate on the "executor_id" field.
func ExecutorIDGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldExecutorID, v))
}

// ExecutorIDGTE applies the GTE predicate on the "executor_id" field.
func ExecutorIDGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldExecutorID, v))
}

// ExecutorIDLT applies the LT predicate on the "executor_id" field.
func ExecutorIDLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldExecutorID, v))
}

// ExecutorIDLTE applies the LTE predicate on the "executor_id" field.
func ExecutorIDLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldExecutorID, v))
}

// ExecutorIDContains applies the Contains predicate on the "executor_id" field.
func ExecutorIDContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldExecutorID, v))
}

// ExecutorIDHasPrefix applies the HasPrefix predicate on the "executor_id" field.
func ExecutorIDHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldExecutorID, v))
}

// ExecutorIDHasSuffix applies the HasSuffix predicate on the "executor_id" field.
func ExecutorIDHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldExecutorID, v))
}

// ExecutorIDEqualFold applies the EqualFold predicate on the "executor_id" field.
func ExecutorIDEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldExecutorID, v))
}

// ExecutorIDContainsFold applies the ContainsFold predicate on the "executor_id" field.
func ExecutorIDContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldExecutorID, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldPayloadJSON, v))
}

// PayloadJSONContains applies the Contains predicate on the "payload_json" field.
func PayloadJSONContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldPayloadJSON, v))
}

// PayloadJSONHasPrefix applies the HasPrefix predicate on the "payload_json" field.
func PayloadJSONHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldPayloadJSON, v))
}

// PayloadJSONHasSuffix applies the HasSuffix predicate on the "payload_json" field.
func PayloadJSONHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldPayloadJSON, v))
}

// PayloadJSONEqualFold applies the EqualFold predicate on the "payload_json" field.
func PayloadJSONEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldPayloadJSON, v))
}

// PayloadJSONContainsFold applies the ContainsFold predicate on the "payload_json" field.
func PayloadJSONContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldPayloadJSON, v))
}

// ConditionResultsJSONEQ applies the EQ predicate on the "condition_results_json" field.
func ConditionResultsJSONEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONNEQ applies the NEQ predicate on the "condition_results_json" field.
func ConditionResultsJSONNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONIn applies the In predicate on the "condition_results_json" field.
func ConditionResultsJSONIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldConditionResultsJSON, vs...))
}

// ConditionResultsJSONNotIn applies the NotIn predicate on the "condition_results_json" field.
func ConditionResultsJSONNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldConditionResultsJSON, vs...))
}

// ConditionResultsJSONGT applies the GT predicate on the "condition_results_json" field.
func ConditionResultsJSONGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONGTE applies the GTE predicate on the "condition_results_json" field.
func ConditionResultsJSONGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONLT applies the LT predicate on the "condition_results_json" field.
func ConditionResultsJSONLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONLTE applies the LTE predicate on the "condition_results_json" field.
func ConditionResultsJSONLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONContains applies the Contains predicate on the "condition_results_json" field.
func ConditionResultsJSONContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONHasPrefix applies the HasPrefix predicate on the "condition_results_json" field.
func ConditionResultsJSONHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONHasSuffix applies the HasSuffix predicate on the "condition_results_json" field.
func ConditionResultsJSONHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONEqualFold applies the EqualFold predicate on the "condition_results_json" field.
func ConditionResultsJSONEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldConditionResultsJSON, v))
}

// ConditionResultsJSONContainsFold applies the ContainsFold predicate on the "condition_results_json" field.
func ConditionResultsJSONContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldConditionResultsJSON, v))
}

// NextsIsNil applies the IsNil predicate on the "nexts" field.
func NextsIsNil() predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIsNull(FieldNexts))
}

// NextsNotNil applies the NotNil predicate on the "nexts" field.
func NextsNotNil() predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotNull(FieldNexts))
}

// ConditionErrorEQ applies the EQ predicate on the "condition_error" field.
func ConditionErrorEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldConditionError, v))
}

// ConditionErrorNEQ applies the NEQ predicate on the "condition_error" field.
func ConditionErrorNEQ(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldConditionError, v))
}

// ConditionErrorIn applies the In predicate on the "condition_error" field.
func ConditionErrorIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldConditionError, vs...))
}

// ConditionErrorNotIn applies the NotIn predicate on the "condition_error" field.
func ConditionErrorNotIn(vs ...string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldConditionError, vs...))
}

// ConditionErrorGT applies the GT predicate on the "condition_error" field.
func ConditionErrorGT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldConditionError, v))
}

// ConditionErrorGTE applies the GTE predicate on the "condition_error" field.
func ConditionErrorGTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldConditionError, v))
}

// ConditionErrorLT applies the LT predicate on the "condition_error" field.
func ConditionErrorLT(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldConditionError, v))
}

// ConditionErrorLTE applies the LTE predicate on the "condition_error" field.
func ConditionErrorLTE(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldConditionError, v))
}

// ConditionErrorContains applies the Contains predicate on the "condition_error" field.
func ConditionErrorContains(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContains(FieldConditionError, v))
}

// ConditionErrorHasPrefix applies the HasPrefix predicate on the "condition_error" field.
func ConditionErrorHasPrefix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasPrefix(FieldConditionError, v))
}

// ConditionErrorHasSuffix applies the HasSuffix predicate on the "condition_error" field.
func ConditionErrorHasSuffix(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldHasSuffix(FieldConditionError, v))
}

// ConditionErrorEqualFold applies the EqualFold predicate on the "condition_error" field.
func ConditionErrorEqualFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEqualFold(FieldConditionError, v))
}

// ConditionErrorContainsFold applies the ContainsFold predicate on the "condition_error" field.
func ConditionErrorContainsFold(v string) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldContainsFold(FieldConditionError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowResult) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowResult) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowResult) predicate.WorkflowResult {
	return predicate.WorkflowResult(sql.NotPredicates(p))
}
