// Code generated by ent, DO NOT EDIT.

package transfersession

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transfersession type in the database.
	Label = "transfer_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldExecutionID holds the string denoting the execution_id field in the database.
	FieldExecutionID = "execution_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldSenderClientID holds the string denoting the sender_client_id field in the database.
	FieldSenderClientID = "sender_client_id"
	// FieldReceiverClientID holds the string denoting the receiver_client_id field in the database.
	FieldReceiverClientID = "receiver_client_id"
	// FieldReceiverTags holds the string denoting the receiver_tags field in the database.
	FieldReceiverTags = "receiver_tags"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldDestinationFile holds the string denoting the destination_file field in the database.
	FieldDestinationFile = "destination_file"
	// FieldPermissions holds the string denoting the permissions field in the database.
	FieldPermissions = "permissions"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldViaP2p holds the string denoting the via_p2p field in the database.
	FieldViaP2p = "via_p2p"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the transfersession in the database.
	Table = "transfer_sessions"
)

// Columns holds all SQL columns for transfersession fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldWorkflowID,
	FieldExecutionID,
	FieldNodeID,
	FieldSenderClientID,
	FieldReceiverClientID,
	FieldReceiverTags,
	FieldFileName,
	FieldDestinationFile,
	FieldPermissions,
	FieldSize,
	FieldSha256,
	FieldStatus,
	FieldViaP2p,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultWorkflowID holds the default value on creation for the "workflow_id" field.
	DefaultWorkflowID string
	// DefaultExecutionID holds the default value on creation for the "execution_id" field.
	DefaultExecutionID string
	// DefaultNodeID holds the default value on creation for the "node_id" field.
	DefaultNodeID string
	// SenderClientIDValidator is a validator for the "sender_client_id" field. It is called by the builders before save.
	SenderClientIDValidator func(string) error
	// DefaultReceiverClientID holds the default value on creation for the "receiver_client_id" field.
	DefaultReceiverClientID string
	// DefaultFileName holds the default value on creation for the "file_name" field.
	DefaultFileName string
	// DestinationFileValidator is a validator for the "destination_file" field. It is called by the builders before save.
	DestinationFileValidator func(string) error
	// DefaultPermissions holds the default value on creation for the "permissions" field.
	DefaultPermissions string
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultSha256 holds the default value on creation for the "sha256" field.
	DefaultSha256 string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultViaP2p holds the default value on creation for the "via_p2p" field.
	DefaultViaP2p bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the TransferSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByExecutionID orders the results by the execution_id field.
func ByExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// BySenderClientID orders the results by the sender_client_id field.
func BySenderClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderClientID, opts...).ToFunc()
}

// ByReceiverClientID orders the results by the receiver_client_id field.
func ByReceiverClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiverClientID, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByDestinationFile orders the results by the destination_file field.
func ByDestinationFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationFile, opts...).ToFunc()
}

// ByPermissions orders the results by the permissions field.
func ByPermissions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermissions, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByViaP2p orders the results by the via_p2p field.
func ByViaP2p(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViaP2p, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
