// Code generated by ent, DO NOT EDIT.

package transfersession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mcmx/nitejaguar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldTenantID, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldWorkflowID, v))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldExecutionID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldNodeID, v))
}

// SenderClientID applies equality check predicate on the "sender_client_id" field. It's identical to SenderClientIDEQ.
func SenderClientID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSenderClientID, v))
}

// ReceiverClientID applies equality check predicate on the "receiver_client_id" field. It's identical to ReceiverClientIDEQ.
func ReceiverClientID(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldReceiverClientID, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldFileName, v))
}

// DestinationFile applies equality check predicate on the "destination_file" field. It's identical to DestinationFileEQ.
func DestinationFile(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldDestinationFile, v))
}

// Permissions applies equality check predicate on the "permissions" field. It's identical to PermissionsEQ.
func Permissions(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldPermissions, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSize, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSha256, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldStatus, v))
}

// ViaP2p applies equality check predicate on the "via_p2p" field. It's identical to ViaP2pEQ.
func ViaP2p(v bool) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldViaP2p, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldTenantID, v))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDContains applies the Contains predicate on the "workflow_id" field.
func WorkflowIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldWorkflowID, v))
}

// WorkflowIDHasPrefix applies the HasPrefix predicate on the "workflow_id" field.
func WorkflowIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldWorkflowID, v))
}

// WorkflowIDHasSuffix applies the HasSuffix predicate on the "workflow_id" field.
func WorkflowIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldWorkflowID, v))
}

// WorkflowIDEqualFold applies the EqualFold predicate on the "workflow_id" field.
func WorkflowIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldWorkflowID, v))
}

// WorkflowIDContainsFold applies the ContainsFold predicate on the "workflow_id" field.
func WorkflowIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldWorkflowID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldExecutionID, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldNodeID, v))
}

// SenderClientIDEQ applies the EQ predicate on the "sender_client_id" field.
func SenderClientIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSenderClientID, v))
}

// SenderClientIDNEQ applies the NEQ predicate on the "sender_client_id" field.
func SenderClientIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldSenderClientID, v))
}

// SenderClientIDIn applies the In predicate on the "sender_client_id" field.
func SenderClientIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldSenderClientID, vs...))
}

// SenderClientIDNotIn applies the NotIn predicate on the "sender_client_id" field.
func SenderClientIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldSenderClientID, vs...))
}

// SenderClientIDGT applies the GT predicate on the "sender_client_id" field.
func SenderClientIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldSenderClientID, v))
}

// SenderClientIDGTE applies the GTE predicate on the "sender_client_id" field.
func SenderClientIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldSenderClientID, v))
}

// SenderClientIDLT applies the LT predicate on the "sender_client_id" field.
func SenderClientIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldSenderClientID, v))
}

// SenderClientIDLTE applies the LTE predicate on the "sender_client_id" field.
func SenderClientIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldSenderClientID, v))
}

// SenderClientIDContains applies the Contains predicate on the "sender_client_id" field.
func SenderClientIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldSenderClientID, v))
}

// SenderClientIDHasPrefix applies the HasPrefix predicate on the "sender_client_id" field.
func SenderClientIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldSenderClientID, v))
}

// SenderClientIDHasSuffix applies the HasSuffix predicate on the "sender_client_id" field.
func SenderClientIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldSenderClientID, v))
}

// SenderClientIDEqualFold applies the EqualFold predicate on the "sender_client_id" field.
func SenderClientIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldSenderClientID, v))
}

// SenderClientIDContainsFold applies the ContainsFold predicate on the "sender_client_id" field.
func SenderClientIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldSenderClientID, v))
}

// ReceiverClientIDEQ applies the EQ predicate on the "receiver_client_id" field.
func ReceiverClientIDEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldReceiverClientID, v))
}

// ReceiverClientIDNEQ applies the NEQ predicate on the "receiver_client_id" field.
func ReceiverClientIDNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldReceiverClientID, v))
}

// ReceiverClientIDIn applies the In predicate on the "receiver_client_id" field.
func ReceiverClientIDIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldReceiverClientID, vs...))
}

// ReceiverClientIDNotIn applies the NotIn predicate on the "receiver_client_id" field.
func ReceiverClientIDNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldReceiverClientID, vs...))
}

// ReceiverClientIDGT applies the GT predicate on the "receiver_client_id" field.
func ReceiverClientIDGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldReceiverClientID, v))
}

// ReceiverClientIDGTE applies the GTE predicate on the "receiver_client_id" field.
func ReceiverClientIDGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldReceiverClientID, v))
}

// ReceiverClientIDLT applies the LT predicate on the "receiver_client_id" field.
func ReceiverClientIDLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldReceiverClientID, v))
}

// ReceiverClientIDLTE applies the LTE predicate on the "receiver_client_id" field.
func ReceiverClientIDLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldReceiverClientID, v))
}

// ReceiverClientIDContains applies the Contains predicate on the "receiver_client_id" field.
func ReceiverClientIDContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldReceiverClientID, v))
}

// ReceiverClientIDHasPrefix applies the HasPrefix predicate on the "receiver_client_id" field.
func ReceiverClientIDHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldReceiverClientID, v))
}

// ReceiverClientIDHasSuffix applies the HasSuffix predicate on the "receiver_client_id" field.
func ReceiverClientIDHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldReceiverClientID, v))
}

// ReceiverClientIDEqualFold applies the EqualFold predicate on the "receiver_client_id" field.
func ReceiverClientIDEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldReceiverClientID, v))
}

// ReceiverClientIDContainsFold applies the ContainsFold predicate on the "receiver_client_id" field.
func ReceiverClientIDContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldReceiverClientID, v))
}

// ReceiverTagsIsNil applies the IsNil predicate on the "receiver_tags" field.
func ReceiverTagsIsNil() predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIsNull(FieldReceiverTags))
}

// ReceiverTagsNotNil applies the NotNil predicate on the "receiver_tags" field.
func ReceiverTagsNotNil() predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotNull(FieldReceiverTags))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldFileName, v))
}

// DestinationFileEQ applies the EQ predicate on the "destination_file" field.
func DestinationFileEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldDestinationFile, v))
}

// DestinationFileNEQ applies the NEQ predicate on the "destination_file" field.
func DestinationFileNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldDestinationFile, v))
}

// DestinationFileIn applies the In predicate on the "destination_file" field.
func DestinationFileIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldDestinationFile, vs...))
}

// DestinationFileNotIn applies the NotIn predicate on the "destination_file" field.
func DestinationFileNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldDestinationFile, vs...))
}

// DestinationFileGT applies the GT predicate on the "destination_file" field.
func DestinationFileGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldDestinationFile, v))
}

// DestinationFileGTE applies the GTE predicate on the "destination_file" field.
func DestinationFileGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldDestinationFile, v))
}

// DestinationFileLT applies the LT predicate on the "destination_file" field.
func DestinationFileLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldDestinationFile, v))
}

// DestinationFileLTE applies the LTE predicate on the "destination_file" field.
func DestinationFileLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldDestinationFile, v))
}

// DestinationFileContains applies the Contains predicate on the "destination_file" field.
func DestinationFileContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldDestinationFile, v))
}

// DestinationFileHasPrefix applies the HasPrefix predicate on the "destination_file" field.
func DestinationFileHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldDestinationFile, v))
}

// DestinationFileHasSuffix applies the HasSuffix predicate on the "destination_file" field.
func DestinationFileHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldDestinationFile, v))
}

// DestinationFileEqualFold applies the EqualFold predicate on the "destination_file" field.
func DestinationFileEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldDestinationFile, v))
}

// DestinationFileContainsFold applies the ContainsFold predicate on the "destination_file" field.
func DestinationFileContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldDestinationFile, v))
}

// PermissionsEQ applies the EQ predicate on the "permissions" field.
func PermissionsEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldPermissions, v))
}

// PermissionsNEQ applies the NEQ predicate on the "permissions" field.
func PermissionsNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldPermissions, v))
}

// PermissionsIn applies the In predicate on the "permissions" field.
func PermissionsIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldPermissions, vs...))
}

// PermissionsNotIn applies the NotIn predicate on the "permissions" field.
func PermissionsNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldPermissions, vs...))
}

// PermissionsGT applies the GT predicate on the "permissions" field.
func PermissionsGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldPermissions, v))
}

// PermissionsGTE applies the GTE predicate on the "permissions" field.
func PermissionsGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldPermissions, v))
}

// PermissionsLT applies the LT predicate on the "permissions" field.
func PermissionsLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldPermissions, v))
}

// PermissionsLTE applies the LTE predicate on the "permissions" field.
func PermissionsLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldPermissions, v))
}

// PermissionsContains applies the Contains predicate on the "permissions" field.
func PermissionsContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldPermissions, v))
}

// PermissionsHasPrefix applies the HasPrefix predicate on the "permissions" field.
func PermissionsHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldPermissions, v))
}

// PermissionsHasSuffix applies the HasSuffix predicate on the "permissions" field.
func PermissionsHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldPermissions, v))
}

// PermissionsEqualFold applies the EqualFold predicate on the "permissions" field.
func PermissionsEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldPermissions, v))
}

// PermissionsContainsFold applies the ContainsFold predicate on the "permissions" field.
func PermissionsContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldPermissions, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldSize, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldSha256, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldContainsFold(FieldStatus, v))
}

// ViaP2pEQ applies the EQ predicate on the "via_p2p" field.
func ViaP2pEQ(v bool) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldViaP2p, v))
}

// ViaP2pNEQ applies the NEQ predicate on the "via_p2p" field.
func ViaP2pNEQ(v bool) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldViaP2p, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TransferSession {
	return predicate.TransferSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransferSession) predicate.TransferSession {
	return predicate.TransferSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransferSession) predicate.TransferSession {
	return predicate.TransferSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransferSession) predicate.TransferSession {
	return predicate.TransferSession(sql.NotPredicates(p))
}
