name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Run templ generate
        shell: bash
        run: templ generate -path .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64